'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace MenuServiceRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MenuProgramAccessDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/TelerikMenuBackCls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MenuProgramAccessDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CACCESS_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCOMPANY_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CMENU_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CMENU_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CPROGRAM_IDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CACCESS_ID() As String
            Get
                Return Me.CACCESS_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CACCESS_IDField, value) <> true) Then
                    Me.CACCESS_IDField = value
                    Me.RaisePropertyChanged("CACCESS_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CCOMPANY_ID() As String
            Get
                Return Me.CCOMPANY_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CCOMPANY_IDField, value) <> true) Then
                    Me.CCOMPANY_IDField = value
                    Me.RaisePropertyChanged("CCOMPANY_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CMENU_ID() As String
            Get
                Return Me.CMENU_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CMENU_IDField, value) <> true) Then
                    Me.CMENU_IDField = value
                    Me.RaisePropertyChanged("CMENU_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CMENU_NAME() As String
            Get
                Return Me.CMENU_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CMENU_NAMEField, value) <> true) Then
                    Me.CMENU_NAMEField = value
                    Me.RaisePropertyChanged("CMENU_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CPROGRAM_ID() As String
            Get
                Return Me.CPROGRAM_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CPROGRAM_IDField, value) <> true) Then
                    Me.CPROGRAM_IDField = value
                    Me.RaisePropertyChanged("CPROGRAM_ID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MenuDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/TelerikMenuBackCls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MenuDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCOMPANY_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CMENU_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CMENU_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CPARENT_SUB_MENU_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CSUB_MENU_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CSUB_MENU_IMAGEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CSUB_MENU_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CSUB_MENU_TOOL_TIPField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CSUB_MENU_TYPEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CUSER_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ICOLUMN_INDEXField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IFAVORITE_INDEXField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IGROUP_INDEXField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ILEVELField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IROW_INDEXField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LFAVORITEField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CCOMPANY_ID() As String
            Get
                Return Me.CCOMPANY_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CCOMPANY_IDField, value) <> true) Then
                    Me.CCOMPANY_IDField = value
                    Me.RaisePropertyChanged("CCOMPANY_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CMENU_ID() As String
            Get
                Return Me.CMENU_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CMENU_IDField, value) <> true) Then
                    Me.CMENU_IDField = value
                    Me.RaisePropertyChanged("CMENU_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CMENU_NAME() As String
            Get
                Return Me.CMENU_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CMENU_NAMEField, value) <> true) Then
                    Me.CMENU_NAMEField = value
                    Me.RaisePropertyChanged("CMENU_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CPARENT_SUB_MENU_ID() As String
            Get
                Return Me.CPARENT_SUB_MENU_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CPARENT_SUB_MENU_IDField, value) <> true) Then
                    Me.CPARENT_SUB_MENU_IDField = value
                    Me.RaisePropertyChanged("CPARENT_SUB_MENU_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CSUB_MENU_ID() As String
            Get
                Return Me.CSUB_MENU_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CSUB_MENU_IDField, value) <> true) Then
                    Me.CSUB_MENU_IDField = value
                    Me.RaisePropertyChanged("CSUB_MENU_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CSUB_MENU_IMAGE() As String
            Get
                Return Me.CSUB_MENU_IMAGEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CSUB_MENU_IMAGEField, value) <> true) Then
                    Me.CSUB_MENU_IMAGEField = value
                    Me.RaisePropertyChanged("CSUB_MENU_IMAGE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CSUB_MENU_NAME() As String
            Get
                Return Me.CSUB_MENU_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CSUB_MENU_NAMEField, value) <> true) Then
                    Me.CSUB_MENU_NAMEField = value
                    Me.RaisePropertyChanged("CSUB_MENU_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CSUB_MENU_TOOL_TIP() As String
            Get
                Return Me.CSUB_MENU_TOOL_TIPField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CSUB_MENU_TOOL_TIPField, value) <> true) Then
                    Me.CSUB_MENU_TOOL_TIPField = value
                    Me.RaisePropertyChanged("CSUB_MENU_TOOL_TIP")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CSUB_MENU_TYPE() As String
            Get
                Return Me.CSUB_MENU_TYPEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CSUB_MENU_TYPEField, value) <> true) Then
                    Me.CSUB_MENU_TYPEField = value
                    Me.RaisePropertyChanged("CSUB_MENU_TYPE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CUSER_ID() As String
            Get
                Return Me.CUSER_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CUSER_IDField, value) <> true) Then
                    Me.CUSER_IDField = value
                    Me.RaisePropertyChanged("CUSER_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ICOLUMN_INDEX() As System.Nullable(Of Integer)
            Get
                Return Me.ICOLUMN_INDEXField
            End Get
            Set
                If (Me.ICOLUMN_INDEXField.Equals(value) <> true) Then
                    Me.ICOLUMN_INDEXField = value
                    Me.RaisePropertyChanged("ICOLUMN_INDEX")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IFAVORITE_INDEX() As System.Nullable(Of Integer)
            Get
                Return Me.IFAVORITE_INDEXField
            End Get
            Set
                If (Me.IFAVORITE_INDEXField.Equals(value) <> true) Then
                    Me.IFAVORITE_INDEXField = value
                    Me.RaisePropertyChanged("IFAVORITE_INDEX")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IGROUP_INDEX() As System.Nullable(Of Integer)
            Get
                Return Me.IGROUP_INDEXField
            End Get
            Set
                If (Me.IGROUP_INDEXField.Equals(value) <> true) Then
                    Me.IGROUP_INDEXField = value
                    Me.RaisePropertyChanged("IGROUP_INDEX")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ILEVEL() As Integer
            Get
                Return Me.ILEVELField
            End Get
            Set
                If (Me.ILEVELField.Equals(value) <> true) Then
                    Me.ILEVELField = value
                    Me.RaisePropertyChanged("ILEVEL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IROW_INDEX() As System.Nullable(Of Integer)
            Get
                Return Me.IROW_INDEXField
            End Get
            Set
                If (Me.IROW_INDEXField.Equals(value) <> true) Then
                    Me.IROW_INDEXField = value
                    Me.RaisePropertyChanged("IROW_INDEX")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LFAVORITE() As Boolean
            Get
                Return Me.LFAVORITEField
            End Get
            Set
                If (Me.LFAVORITEField.Equals(value) <> true) Then
                    Me.LFAVORITEField = value
                    Me.RaisePropertyChanged("LFAVORITE")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SAM_USER_COMPANYDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/TelerikMenuBackCls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SAM_USER_COMPANYDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCOMPANY_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CUSER_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LCAN_BROADCASTField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CCOMPANY_ID() As String
            Get
                Return Me.CCOMPANY_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CCOMPANY_IDField, value) <> true) Then
                    Me.CCOMPANY_IDField = value
                    Me.RaisePropertyChanged("CCOMPANY_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CUSER_ID() As String
            Get
                Return Me.CUSER_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CUSER_IDField, value) <> true) Then
                    Me.CUSER_IDField = value
                    Me.RaisePropertyChanged("CUSER_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LCAN_BROADCAST() As Boolean
            Get
                Return Me.LCAN_BROADCASTField
            End Get
            Set
                If (Me.LCAN_BROADCASTField.Equals(value) <> true) Then
                    Me.LCAN_BROADCASTField = value
                    Me.RaisePropertyChanged("LCAN_BROADCAST")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="MenuServiceRef.IMenuService")>  _
    Public Interface IMenuService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/getMenuAccess", ReplyAction:="http://tempuri.org/IMenuService/getMenuAccessResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/getMenuAccessR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function getMenuAccess(ByVal pcCompanyId As String, ByVal pcUserId As String) As System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/getMenuAccess", ReplyAction:="http://tempuri.org/IMenuService/getMenuAccessResponse")>  _
        Function BegingetMenuAccess(ByVal pcCompanyId As String, ByVal pcUserId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndgetMenuAccess(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/getLastId", ReplyAction:="http://tempuri.org/IMenuService/getLastIdResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/getLastIdR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function getLastId(ByVal pcCompanyId As String, ByVal pcUserId As String, ByVal pcMENU_ID As String, ByVal pcSUB_MENU_TYPE As String) As MenuServiceRef.MenuDTO
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/getLastId", ReplyAction:="http://tempuri.org/IMenuService/getLastIdResponse")>  _
        Function BegingetLastId(ByVal pcCompanyId As String, ByVal pcUserId As String, ByVal pcMENU_ID As String, ByVal pcSUB_MENU_TYPE As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndgetLastId(ByVal result As System.IAsyncResult) As MenuServiceRef.MenuDTO
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/insertMenuToDB", ReplyAction:="http://tempuri.org/IMenuService/insertMenuToDBResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/insertMenuToDBR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub insertMenuToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/insertMenuToDB", ReplyAction:="http://tempuri.org/IMenuService/insertMenuToDBResponse")>  _
        Function BegininsertMenuToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndinsertMenuToDB(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/deleteMenuFromDB", ReplyAction:="http://tempuri.org/IMenuService/deleteMenuFromDBResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/deleteMenuFromDBR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub deleteMenuFromDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/deleteMenuFromDB", ReplyAction:="http://tempuri.org/IMenuService/deleteMenuFromDBResponse")>  _
        Function BegindeleteMenuFromDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EnddeleteMenuFromDB(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/updateMenuNameToDB", ReplyAction:="http://tempuri.org/IMenuService/updateMenuNameToDBResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/updateMenuNameToDBR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub updateMenuNameToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/updateMenuNameToDB", ReplyAction:="http://tempuri.org/IMenuService/updateMenuNameToDBResponse")>  _
        Function BeginupdateMenuNameToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndupdateMenuNameToDB(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/updateGroupIndexToDB", ReplyAction:="http://tempuri.org/IMenuService/updateGroupIndexToDBResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/updateGroupIndexToDBR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub updateGroupIndexToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal pcOperation As String)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/updateGroupIndexToDB", ReplyAction:="http://tempuri.org/IMenuService/updateGroupIndexToDBResponse")>  _
        Function BeginupdateGroupIndexToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal pcOperation As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndupdateGroupIndexToDB(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/updateMenuPositionToDB", ReplyAction:="http://tempuri.org/IMenuService/updateMenuPositionToDBResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/updateMenuPositionToDBR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub updateMenuPositionToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/updateMenuPositionToDB", ReplyAction:="http://tempuri.org/IMenuService/updateMenuPositionToDBResponse")>  _
        Function BeginupdateMenuPositionToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndupdateMenuPositionToDB(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/_getProgramImage", ReplyAction:="http://tempuri.org/IMenuService/_getProgramImageResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/_getProgramImageR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function _getProgramImage(ByVal poMenuDTO As MenuServiceRef.MenuDTO) As String
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/_getProgramImage", ReplyAction:="http://tempuri.org/IMenuService/_getProgramImageResponse")>  _
        Function Begin_getProgramImage(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function End_getProgramImage(ByVal result As System.IAsyncResult) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/saveMenuFavourite", ReplyAction:="http://tempuri.org/IMenuService/saveMenuFavouriteResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/saveMenuFavouriteR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub saveMenuFavourite(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/saveMenuFavourite", ReplyAction:="http://tempuri.org/IMenuService/saveMenuFavouriteResponse")>  _
        Function BeginsaveMenuFavourite(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndsaveMenuFavourite(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/deleteMenuFavourite", ReplyAction:="http://tempuri.org/IMenuService/deleteMenuFavouriteResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/deleteMenuFavouriteR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub deleteMenuFavourite(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/deleteMenuFavourite", ReplyAction:="http://tempuri.org/IMenuService/deleteMenuFavouriteResponse")>  _
        Function BegindeleteMenuFavourite(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EnddeleteMenuFavourite(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/svc_getCompanyList", ReplyAction:="http://tempuri.org/IMenuService/svc_getCompanyListResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/svc_getCompanyListR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function svc_getCompanyList(ByVal pcUserId As String, ByVal pcCompanyId As String) As System.Collections.Generic.List(Of MenuServiceRef.SAM_USER_COMPANYDTO)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/svc_getCompanyList", ReplyAction:="http://tempuri.org/IMenuService/svc_getCompanyListResponse")>  _
        Function Beginsvc_getCompanyList(ByVal pcUserId As String, ByVal pcCompanyId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function Endsvc_getCompanyList(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of MenuServiceRef.SAM_USER_COMPANYDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/checkMenuFavourite", ReplyAction:="http://tempuri.org/IMenuService/checkMenuFavouriteResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/checkMenuFavouriteR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function checkMenuFavourite(ByVal poMenuDTO As MenuServiceRef.MenuDTO) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/checkMenuFavourite", ReplyAction:="http://tempuri.org/IMenuService/checkMenuFavouriteResponse")>  _
        Function BegincheckMenuFavourite(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndcheckMenuFavourite(ByVal result As System.IAsyncResult) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/getSecurity", ReplyAction:="http://tempuri.org/IMenuService/getSecurityResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/getSecurityR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function getSecurity() As Boolean
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/getSecurity", ReplyAction:="http://tempuri.org/IMenuService/getSecurityResponse")>  _
        Function BegingetSecurity(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndgetSecurity(ByVal result As System.IAsyncResult) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/getAccessButton", ReplyAction:="http://tempuri.org/IMenuService/getAccessButtonResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/getAccessButtonR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function getAccessButton(ByVal pcCompId As String, ByVal pcProgId As String) As System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/getAccessButton", ReplyAction:="http://tempuri.org/IMenuService/getAccessButtonResponse")>  _
        Function BegingetAccessButton(ByVal pcCompId As String, ByVal pcProgId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndgetAccessButton(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuService/SaveHistory", ReplyAction:="http://tempuri.org/IMenuService/SaveHistoryResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuService/SaveHistoryR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub SaveHistory(ByVal pcCompId As String, ByVal pcUserId As String, ByVal pcProgId As String, ByVal pcAction As String)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuService/SaveHistory", ReplyAction:="http://tempuri.org/IMenuService/SaveHistoryResponse")>  _
        Function BeginSaveHistory(ByVal pcCompId As String, ByVal pcUserId As String, ByVal pcProgId As String, ByVal pcAction As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndSaveHistory(ByVal result As System.IAsyncResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IMenuServiceChannel
        Inherits MenuServiceRef.IMenuService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class getMenuAccessCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO)
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO))
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class getLastIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As MenuServiceRef.MenuDTO
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MenuServiceRef.MenuDTO)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class _getProgramImageCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class svc_getCompanyListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.Collections.Generic.List(Of MenuServiceRef.SAM_USER_COMPANYDTO)
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Collections.Generic.List(Of MenuServiceRef.SAM_USER_COMPANYDTO))
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class checkMenuFavouriteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class getSecurityCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class getAccessButtonCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO)
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO))
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MenuServiceClient
        Inherits System.ServiceModel.ClientBase(Of MenuServiceRef.IMenuService)
        Implements MenuServiceRef.IMenuService
        
        Private onBegingetMenuAccessDelegate As BeginOperationDelegate
        
        Private onEndgetMenuAccessDelegate As EndOperationDelegate
        
        Private ongetMenuAccessCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBegingetLastIdDelegate As BeginOperationDelegate
        
        Private onEndgetLastIdDelegate As EndOperationDelegate
        
        Private ongetLastIdCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBegininsertMenuToDBDelegate As BeginOperationDelegate
        
        Private onEndinsertMenuToDBDelegate As EndOperationDelegate
        
        Private oninsertMenuToDBCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBegindeleteMenuFromDBDelegate As BeginOperationDelegate
        
        Private onEnddeleteMenuFromDBDelegate As EndOperationDelegate
        
        Private ondeleteMenuFromDBCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginupdateMenuNameToDBDelegate As BeginOperationDelegate
        
        Private onEndupdateMenuNameToDBDelegate As EndOperationDelegate
        
        Private onupdateMenuNameToDBCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginupdateGroupIndexToDBDelegate As BeginOperationDelegate
        
        Private onEndupdateGroupIndexToDBDelegate As EndOperationDelegate
        
        Private onupdateGroupIndexToDBCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginupdateMenuPositionToDBDelegate As BeginOperationDelegate
        
        Private onEndupdateMenuPositionToDBDelegate As EndOperationDelegate
        
        Private onupdateMenuPositionToDBCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBegin_getProgramImageDelegate As BeginOperationDelegate
        
        Private onEnd_getProgramImageDelegate As EndOperationDelegate
        
        Private on_getProgramImageCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginsaveMenuFavouriteDelegate As BeginOperationDelegate
        
        Private onEndsaveMenuFavouriteDelegate As EndOperationDelegate
        
        Private onsaveMenuFavouriteCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBegindeleteMenuFavouriteDelegate As BeginOperationDelegate
        
        Private onEnddeleteMenuFavouriteDelegate As EndOperationDelegate
        
        Private ondeleteMenuFavouriteCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginsvc_getCompanyListDelegate As BeginOperationDelegate
        
        Private onEndsvc_getCompanyListDelegate As EndOperationDelegate
        
        Private onsvc_getCompanyListCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBegincheckMenuFavouriteDelegate As BeginOperationDelegate
        
        Private onEndcheckMenuFavouriteDelegate As EndOperationDelegate
        
        Private oncheckMenuFavouriteCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBegingetSecurityDelegate As BeginOperationDelegate
        
        Private onEndgetSecurityDelegate As EndOperationDelegate
        
        Private ongetSecurityCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBegingetAccessButtonDelegate As BeginOperationDelegate
        
        Private onEndgetAccessButtonDelegate As EndOperationDelegate
        
        Private ongetAccessButtonCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginSaveHistoryDelegate As BeginOperationDelegate
        
        Private onEndSaveHistoryDelegate As EndOperationDelegate
        
        Private onSaveHistoryCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event getMenuAccessCompleted As System.EventHandler(Of getMenuAccessCompletedEventArgs)
        
        Public Event getLastIdCompleted As System.EventHandler(Of getLastIdCompletedEventArgs)
        
        Public Event insertMenuToDBCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event deleteMenuFromDBCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event updateMenuNameToDBCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event updateGroupIndexToDBCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event updateMenuPositionToDBCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event _getProgramImageCompleted As System.EventHandler(Of _getProgramImageCompletedEventArgs)
        
        Public Event saveMenuFavouriteCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event deleteMenuFavouriteCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event svc_getCompanyListCompleted As System.EventHandler(Of svc_getCompanyListCompletedEventArgs)
        
        Public Event checkMenuFavouriteCompleted As System.EventHandler(Of checkMenuFavouriteCompletedEventArgs)
        
        Public Event getSecurityCompleted As System.EventHandler(Of getSecurityCompletedEventArgs)
        
        Public Event getAccessButtonCompleted As System.EventHandler(Of getAccessButtonCompletedEventArgs)
        
        Public Event SaveHistoryCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Function getMenuAccess(ByVal pcCompanyId As String, ByVal pcUserId As String) As System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO) Implements MenuServiceRef.IMenuService.getMenuAccess
            Return MyBase.Channel.getMenuAccess(pcCompanyId, pcUserId)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegingetMenuAccess(ByVal pcCompanyId As String, ByVal pcUserId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.BegingetMenuAccess
            Return MyBase.Channel.BegingetMenuAccess(pcCompanyId, pcUserId, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndgetMenuAccess(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO) Implements MenuServiceRef.IMenuService.EndgetMenuAccess
            Return MyBase.Channel.EndgetMenuAccess(result)
        End Function
        
        Private Function OnBegingetMenuAccess(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pcCompanyId As String = CType(inValues(0),String)
            Dim pcUserId As String = CType(inValues(1),String)
            Return Me.BegingetMenuAccess(pcCompanyId, pcUserId, callback, asyncState)
        End Function
        
        Private Function OnEndgetMenuAccess(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO) = Me.EndgetMenuAccess(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OngetMenuAccessCompleted(ByVal state As Object)
            If (Not (Me.getMenuAccessCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent getMenuAccessCompleted(Me, New getMenuAccessCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub getMenuAccessAsync(ByVal pcCompanyId As String, ByVal pcUserId As String)
            Me.getMenuAccessAsync(pcCompanyId, pcUserId, Nothing)
        End Sub
        
        Public Overloads Sub getMenuAccessAsync(ByVal pcCompanyId As String, ByVal pcUserId As String, ByVal userState As Object)
            If (Me.onBegingetMenuAccessDelegate Is Nothing) Then
                Me.onBegingetMenuAccessDelegate = AddressOf Me.OnBegingetMenuAccess
            End If
            If (Me.onEndgetMenuAccessDelegate Is Nothing) Then
                Me.onEndgetMenuAccessDelegate = AddressOf Me.OnEndgetMenuAccess
            End If
            If (Me.ongetMenuAccessCompletedDelegate Is Nothing) Then
                Me.ongetMenuAccessCompletedDelegate = AddressOf Me.OngetMenuAccessCompleted
            End If
            MyBase.InvokeAsync(Me.onBegingetMenuAccessDelegate, New Object() {pcCompanyId, pcUserId}, Me.onEndgetMenuAccessDelegate, Me.ongetMenuAccessCompletedDelegate, userState)
        End Sub
        
        Public Function getLastId(ByVal pcCompanyId As String, ByVal pcUserId As String, ByVal pcMENU_ID As String, ByVal pcSUB_MENU_TYPE As String) As MenuServiceRef.MenuDTO Implements MenuServiceRef.IMenuService.getLastId
            Return MyBase.Channel.getLastId(pcCompanyId, pcUserId, pcMENU_ID, pcSUB_MENU_TYPE)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegingetLastId(ByVal pcCompanyId As String, ByVal pcUserId As String, ByVal pcMENU_ID As String, ByVal pcSUB_MENU_TYPE As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.BegingetLastId
            Return MyBase.Channel.BegingetLastId(pcCompanyId, pcUserId, pcMENU_ID, pcSUB_MENU_TYPE, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndgetLastId(ByVal result As System.IAsyncResult) As MenuServiceRef.MenuDTO Implements MenuServiceRef.IMenuService.EndgetLastId
            Return MyBase.Channel.EndgetLastId(result)
        End Function
        
        Private Function OnBegingetLastId(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pcCompanyId As String = CType(inValues(0),String)
            Dim pcUserId As String = CType(inValues(1),String)
            Dim pcMENU_ID As String = CType(inValues(2),String)
            Dim pcSUB_MENU_TYPE As String = CType(inValues(3),String)
            Return Me.BegingetLastId(pcCompanyId, pcUserId, pcMENU_ID, pcSUB_MENU_TYPE, callback, asyncState)
        End Function
        
        Private Function OnEndgetLastId(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As MenuServiceRef.MenuDTO = Me.EndgetLastId(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OngetLastIdCompleted(ByVal state As Object)
            If (Not (Me.getLastIdCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent getLastIdCompleted(Me, New getLastIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub getLastIdAsync(ByVal pcCompanyId As String, ByVal pcUserId As String, ByVal pcMENU_ID As String, ByVal pcSUB_MENU_TYPE As String)
            Me.getLastIdAsync(pcCompanyId, pcUserId, pcMENU_ID, pcSUB_MENU_TYPE, Nothing)
        End Sub
        
        Public Overloads Sub getLastIdAsync(ByVal pcCompanyId As String, ByVal pcUserId As String, ByVal pcMENU_ID As String, ByVal pcSUB_MENU_TYPE As String, ByVal userState As Object)
            If (Me.onBegingetLastIdDelegate Is Nothing) Then
                Me.onBegingetLastIdDelegate = AddressOf Me.OnBegingetLastId
            End If
            If (Me.onEndgetLastIdDelegate Is Nothing) Then
                Me.onEndgetLastIdDelegate = AddressOf Me.OnEndgetLastId
            End If
            If (Me.ongetLastIdCompletedDelegate Is Nothing) Then
                Me.ongetLastIdCompletedDelegate = AddressOf Me.OngetLastIdCompleted
            End If
            MyBase.InvokeAsync(Me.onBegingetLastIdDelegate, New Object() {pcCompanyId, pcUserId, pcMENU_ID, pcSUB_MENU_TYPE}, Me.onEndgetLastIdDelegate, Me.ongetLastIdCompletedDelegate, userState)
        End Sub
        
        Public Sub insertMenuToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO) Implements MenuServiceRef.IMenuService.insertMenuToDB
            MyBase.Channel.insertMenuToDB(poMenuDTO)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegininsertMenuToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.BegininsertMenuToDB
            Return MyBase.Channel.BegininsertMenuToDB(poMenuDTO, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndinsertMenuToDB(ByVal result As System.IAsyncResult) Implements MenuServiceRef.IMenuService.EndinsertMenuToDB
            MyBase.Channel.EndinsertMenuToDB(result)
        End Sub
        
        Private Function OnBegininsertMenuToDB(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poMenuDTO As MenuServiceRef.MenuDTO = CType(inValues(0),MenuServiceRef.MenuDTO)
            Return Me.BegininsertMenuToDB(poMenuDTO, callback, asyncState)
        End Function
        
        Private Function OnEndinsertMenuToDB(ByVal result As System.IAsyncResult) As Object()
            Me.EndinsertMenuToDB(result)
            Return Nothing
        End Function
        
        Private Sub OninsertMenuToDBCompleted(ByVal state As Object)
            If (Not (Me.insertMenuToDBCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent insertMenuToDBCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub insertMenuToDBAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
            Me.insertMenuToDBAsync(poMenuDTO, Nothing)
        End Sub
        
        Public Overloads Sub insertMenuToDBAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal userState As Object)
            If (Me.onBegininsertMenuToDBDelegate Is Nothing) Then
                Me.onBegininsertMenuToDBDelegate = AddressOf Me.OnBegininsertMenuToDB
            End If
            If (Me.onEndinsertMenuToDBDelegate Is Nothing) Then
                Me.onEndinsertMenuToDBDelegate = AddressOf Me.OnEndinsertMenuToDB
            End If
            If (Me.oninsertMenuToDBCompletedDelegate Is Nothing) Then
                Me.oninsertMenuToDBCompletedDelegate = AddressOf Me.OninsertMenuToDBCompleted
            End If
            MyBase.InvokeAsync(Me.onBegininsertMenuToDBDelegate, New Object() {poMenuDTO}, Me.onEndinsertMenuToDBDelegate, Me.oninsertMenuToDBCompletedDelegate, userState)
        End Sub
        
        Public Sub deleteMenuFromDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO) Implements MenuServiceRef.IMenuService.deleteMenuFromDB
            MyBase.Channel.deleteMenuFromDB(poMenuDTO)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegindeleteMenuFromDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.BegindeleteMenuFromDB
            Return MyBase.Channel.BegindeleteMenuFromDB(poMenuDTO, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EnddeleteMenuFromDB(ByVal result As System.IAsyncResult) Implements MenuServiceRef.IMenuService.EnddeleteMenuFromDB
            MyBase.Channel.EnddeleteMenuFromDB(result)
        End Sub
        
        Private Function OnBegindeleteMenuFromDB(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poMenuDTO As MenuServiceRef.MenuDTO = CType(inValues(0),MenuServiceRef.MenuDTO)
            Return Me.BegindeleteMenuFromDB(poMenuDTO, callback, asyncState)
        End Function
        
        Private Function OnEnddeleteMenuFromDB(ByVal result As System.IAsyncResult) As Object()
            Me.EnddeleteMenuFromDB(result)
            Return Nothing
        End Function
        
        Private Sub OndeleteMenuFromDBCompleted(ByVal state As Object)
            If (Not (Me.deleteMenuFromDBCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent deleteMenuFromDBCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub deleteMenuFromDBAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
            Me.deleteMenuFromDBAsync(poMenuDTO, Nothing)
        End Sub
        
        Public Overloads Sub deleteMenuFromDBAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal userState As Object)
            If (Me.onBegindeleteMenuFromDBDelegate Is Nothing) Then
                Me.onBegindeleteMenuFromDBDelegate = AddressOf Me.OnBegindeleteMenuFromDB
            End If
            If (Me.onEnddeleteMenuFromDBDelegate Is Nothing) Then
                Me.onEnddeleteMenuFromDBDelegate = AddressOf Me.OnEnddeleteMenuFromDB
            End If
            If (Me.ondeleteMenuFromDBCompletedDelegate Is Nothing) Then
                Me.ondeleteMenuFromDBCompletedDelegate = AddressOf Me.OndeleteMenuFromDBCompleted
            End If
            MyBase.InvokeAsync(Me.onBegindeleteMenuFromDBDelegate, New Object() {poMenuDTO}, Me.onEnddeleteMenuFromDBDelegate, Me.ondeleteMenuFromDBCompletedDelegate, userState)
        End Sub
        
        Public Sub updateMenuNameToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO) Implements MenuServiceRef.IMenuService.updateMenuNameToDB
            MyBase.Channel.updateMenuNameToDB(poMenuDTO)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginupdateMenuNameToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.BeginupdateMenuNameToDB
            Return MyBase.Channel.BeginupdateMenuNameToDB(poMenuDTO, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndupdateMenuNameToDB(ByVal result As System.IAsyncResult) Implements MenuServiceRef.IMenuService.EndupdateMenuNameToDB
            MyBase.Channel.EndupdateMenuNameToDB(result)
        End Sub
        
        Private Function OnBeginupdateMenuNameToDB(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poMenuDTO As MenuServiceRef.MenuDTO = CType(inValues(0),MenuServiceRef.MenuDTO)
            Return Me.BeginupdateMenuNameToDB(poMenuDTO, callback, asyncState)
        End Function
        
        Private Function OnEndupdateMenuNameToDB(ByVal result As System.IAsyncResult) As Object()
            Me.EndupdateMenuNameToDB(result)
            Return Nothing
        End Function
        
        Private Sub OnupdateMenuNameToDBCompleted(ByVal state As Object)
            If (Not (Me.updateMenuNameToDBCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent updateMenuNameToDBCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub updateMenuNameToDBAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
            Me.updateMenuNameToDBAsync(poMenuDTO, Nothing)
        End Sub
        
        Public Overloads Sub updateMenuNameToDBAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal userState As Object)
            If (Me.onBeginupdateMenuNameToDBDelegate Is Nothing) Then
                Me.onBeginupdateMenuNameToDBDelegate = AddressOf Me.OnBeginupdateMenuNameToDB
            End If
            If (Me.onEndupdateMenuNameToDBDelegate Is Nothing) Then
                Me.onEndupdateMenuNameToDBDelegate = AddressOf Me.OnEndupdateMenuNameToDB
            End If
            If (Me.onupdateMenuNameToDBCompletedDelegate Is Nothing) Then
                Me.onupdateMenuNameToDBCompletedDelegate = AddressOf Me.OnupdateMenuNameToDBCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginupdateMenuNameToDBDelegate, New Object() {poMenuDTO}, Me.onEndupdateMenuNameToDBDelegate, Me.onupdateMenuNameToDBCompletedDelegate, userState)
        End Sub
        
        Public Sub updateGroupIndexToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal pcOperation As String) Implements MenuServiceRef.IMenuService.updateGroupIndexToDB
            MyBase.Channel.updateGroupIndexToDB(poMenuDTO, pcOperation)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginupdateGroupIndexToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal pcOperation As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.BeginupdateGroupIndexToDB
            Return MyBase.Channel.BeginupdateGroupIndexToDB(poMenuDTO, pcOperation, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndupdateGroupIndexToDB(ByVal result As System.IAsyncResult) Implements MenuServiceRef.IMenuService.EndupdateGroupIndexToDB
            MyBase.Channel.EndupdateGroupIndexToDB(result)
        End Sub
        
        Private Function OnBeginupdateGroupIndexToDB(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poMenuDTO As MenuServiceRef.MenuDTO = CType(inValues(0),MenuServiceRef.MenuDTO)
            Dim pcOperation As String = CType(inValues(1),String)
            Return Me.BeginupdateGroupIndexToDB(poMenuDTO, pcOperation, callback, asyncState)
        End Function
        
        Private Function OnEndupdateGroupIndexToDB(ByVal result As System.IAsyncResult) As Object()
            Me.EndupdateGroupIndexToDB(result)
            Return Nothing
        End Function
        
        Private Sub OnupdateGroupIndexToDBCompleted(ByVal state As Object)
            If (Not (Me.updateGroupIndexToDBCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent updateGroupIndexToDBCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub updateGroupIndexToDBAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal pcOperation As String)
            Me.updateGroupIndexToDBAsync(poMenuDTO, pcOperation, Nothing)
        End Sub
        
        Public Overloads Sub updateGroupIndexToDBAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal pcOperation As String, ByVal userState As Object)
            If (Me.onBeginupdateGroupIndexToDBDelegate Is Nothing) Then
                Me.onBeginupdateGroupIndexToDBDelegate = AddressOf Me.OnBeginupdateGroupIndexToDB
            End If
            If (Me.onEndupdateGroupIndexToDBDelegate Is Nothing) Then
                Me.onEndupdateGroupIndexToDBDelegate = AddressOf Me.OnEndupdateGroupIndexToDB
            End If
            If (Me.onupdateGroupIndexToDBCompletedDelegate Is Nothing) Then
                Me.onupdateGroupIndexToDBCompletedDelegate = AddressOf Me.OnupdateGroupIndexToDBCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginupdateGroupIndexToDBDelegate, New Object() {poMenuDTO, pcOperation}, Me.onEndupdateGroupIndexToDBDelegate, Me.onupdateGroupIndexToDBCompletedDelegate, userState)
        End Sub
        
        Public Sub updateMenuPositionToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO) Implements MenuServiceRef.IMenuService.updateMenuPositionToDB
            MyBase.Channel.updateMenuPositionToDB(poMenuDTO)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginupdateMenuPositionToDB(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.BeginupdateMenuPositionToDB
            Return MyBase.Channel.BeginupdateMenuPositionToDB(poMenuDTO, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndupdateMenuPositionToDB(ByVal result As System.IAsyncResult) Implements MenuServiceRef.IMenuService.EndupdateMenuPositionToDB
            MyBase.Channel.EndupdateMenuPositionToDB(result)
        End Sub
        
        Private Function OnBeginupdateMenuPositionToDB(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poMenuDTO As MenuServiceRef.MenuDTO = CType(inValues(0),MenuServiceRef.MenuDTO)
            Return Me.BeginupdateMenuPositionToDB(poMenuDTO, callback, asyncState)
        End Function
        
        Private Function OnEndupdateMenuPositionToDB(ByVal result As System.IAsyncResult) As Object()
            Me.EndupdateMenuPositionToDB(result)
            Return Nothing
        End Function
        
        Private Sub OnupdateMenuPositionToDBCompleted(ByVal state As Object)
            If (Not (Me.updateMenuPositionToDBCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent updateMenuPositionToDBCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub updateMenuPositionToDBAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
            Me.updateMenuPositionToDBAsync(poMenuDTO, Nothing)
        End Sub
        
        Public Overloads Sub updateMenuPositionToDBAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal userState As Object)
            If (Me.onBeginupdateMenuPositionToDBDelegate Is Nothing) Then
                Me.onBeginupdateMenuPositionToDBDelegate = AddressOf Me.OnBeginupdateMenuPositionToDB
            End If
            If (Me.onEndupdateMenuPositionToDBDelegate Is Nothing) Then
                Me.onEndupdateMenuPositionToDBDelegate = AddressOf Me.OnEndupdateMenuPositionToDB
            End If
            If (Me.onupdateMenuPositionToDBCompletedDelegate Is Nothing) Then
                Me.onupdateMenuPositionToDBCompletedDelegate = AddressOf Me.OnupdateMenuPositionToDBCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginupdateMenuPositionToDBDelegate, New Object() {poMenuDTO}, Me.onEndupdateMenuPositionToDBDelegate, Me.onupdateMenuPositionToDBCompletedDelegate, userState)
        End Sub
        
        Public Function _getProgramImage(ByVal poMenuDTO As MenuServiceRef.MenuDTO) As String Implements MenuServiceRef.IMenuService._getProgramImage
            Return MyBase.Channel._getProgramImage(poMenuDTO)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function Begin_getProgramImage(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.Begin_getProgramImage
            Return MyBase.Channel.Begin_getProgramImage(poMenuDTO, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function End_getProgramImage(ByVal result As System.IAsyncResult) As String Implements MenuServiceRef.IMenuService.End_getProgramImage
            Return MyBase.Channel.End_getProgramImage(result)
        End Function
        
        Private Function OnBegin_getProgramImage(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poMenuDTO As MenuServiceRef.MenuDTO = CType(inValues(0),MenuServiceRef.MenuDTO)
            Return Me.Begin_getProgramImage(poMenuDTO, callback, asyncState)
        End Function
        
        Private Function OnEnd_getProgramImage(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.End_getProgramImage(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub On_getProgramImageCompleted(ByVal state As Object)
            If (Not (Me._getProgramImageCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent _getProgramImageCompleted(Me, New _getProgramImageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub _getProgramImageAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
            Me._getProgramImageAsync(poMenuDTO, Nothing)
        End Sub
        
        Public Overloads Sub _getProgramImageAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal userState As Object)
            If (Me.onBegin_getProgramImageDelegate Is Nothing) Then
                Me.onBegin_getProgramImageDelegate = AddressOf Me.OnBegin_getProgramImage
            End If
            If (Me.onEnd_getProgramImageDelegate Is Nothing) Then
                Me.onEnd_getProgramImageDelegate = AddressOf Me.OnEnd_getProgramImage
            End If
            If (Me.on_getProgramImageCompletedDelegate Is Nothing) Then
                Me.on_getProgramImageCompletedDelegate = AddressOf Me.On_getProgramImageCompleted
            End If
            MyBase.InvokeAsync(Me.onBegin_getProgramImageDelegate, New Object() {poMenuDTO}, Me.onEnd_getProgramImageDelegate, Me.on_getProgramImageCompletedDelegate, userState)
        End Sub
        
        Public Sub saveMenuFavourite(ByVal poMenuDTO As MenuServiceRef.MenuDTO) Implements MenuServiceRef.IMenuService.saveMenuFavourite
            MyBase.Channel.saveMenuFavourite(poMenuDTO)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginsaveMenuFavourite(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.BeginsaveMenuFavourite
            Return MyBase.Channel.BeginsaveMenuFavourite(poMenuDTO, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndsaveMenuFavourite(ByVal result As System.IAsyncResult) Implements MenuServiceRef.IMenuService.EndsaveMenuFavourite
            MyBase.Channel.EndsaveMenuFavourite(result)
        End Sub
        
        Private Function OnBeginsaveMenuFavourite(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poMenuDTO As MenuServiceRef.MenuDTO = CType(inValues(0),MenuServiceRef.MenuDTO)
            Return Me.BeginsaveMenuFavourite(poMenuDTO, callback, asyncState)
        End Function
        
        Private Function OnEndsaveMenuFavourite(ByVal result As System.IAsyncResult) As Object()
            Me.EndsaveMenuFavourite(result)
            Return Nothing
        End Function
        
        Private Sub OnsaveMenuFavouriteCompleted(ByVal state As Object)
            If (Not (Me.saveMenuFavouriteCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent saveMenuFavouriteCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub saveMenuFavouriteAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
            Me.saveMenuFavouriteAsync(poMenuDTO, Nothing)
        End Sub
        
        Public Overloads Sub saveMenuFavouriteAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal userState As Object)
            If (Me.onBeginsaveMenuFavouriteDelegate Is Nothing) Then
                Me.onBeginsaveMenuFavouriteDelegate = AddressOf Me.OnBeginsaveMenuFavourite
            End If
            If (Me.onEndsaveMenuFavouriteDelegate Is Nothing) Then
                Me.onEndsaveMenuFavouriteDelegate = AddressOf Me.OnEndsaveMenuFavourite
            End If
            If (Me.onsaveMenuFavouriteCompletedDelegate Is Nothing) Then
                Me.onsaveMenuFavouriteCompletedDelegate = AddressOf Me.OnsaveMenuFavouriteCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginsaveMenuFavouriteDelegate, New Object() {poMenuDTO}, Me.onEndsaveMenuFavouriteDelegate, Me.onsaveMenuFavouriteCompletedDelegate, userState)
        End Sub
        
        Public Sub deleteMenuFavourite(ByVal poMenuDTO As MenuServiceRef.MenuDTO) Implements MenuServiceRef.IMenuService.deleteMenuFavourite
            MyBase.Channel.deleteMenuFavourite(poMenuDTO)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegindeleteMenuFavourite(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.BegindeleteMenuFavourite
            Return MyBase.Channel.BegindeleteMenuFavourite(poMenuDTO, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EnddeleteMenuFavourite(ByVal result As System.IAsyncResult) Implements MenuServiceRef.IMenuService.EnddeleteMenuFavourite
            MyBase.Channel.EnddeleteMenuFavourite(result)
        End Sub
        
        Private Function OnBegindeleteMenuFavourite(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poMenuDTO As MenuServiceRef.MenuDTO = CType(inValues(0),MenuServiceRef.MenuDTO)
            Return Me.BegindeleteMenuFavourite(poMenuDTO, callback, asyncState)
        End Function
        
        Private Function OnEnddeleteMenuFavourite(ByVal result As System.IAsyncResult) As Object()
            Me.EnddeleteMenuFavourite(result)
            Return Nothing
        End Function
        
        Private Sub OndeleteMenuFavouriteCompleted(ByVal state As Object)
            If (Not (Me.deleteMenuFavouriteCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent deleteMenuFavouriteCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub deleteMenuFavouriteAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
            Me.deleteMenuFavouriteAsync(poMenuDTO, Nothing)
        End Sub
        
        Public Overloads Sub deleteMenuFavouriteAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal userState As Object)
            If (Me.onBegindeleteMenuFavouriteDelegate Is Nothing) Then
                Me.onBegindeleteMenuFavouriteDelegate = AddressOf Me.OnBegindeleteMenuFavourite
            End If
            If (Me.onEnddeleteMenuFavouriteDelegate Is Nothing) Then
                Me.onEnddeleteMenuFavouriteDelegate = AddressOf Me.OnEnddeleteMenuFavourite
            End If
            If (Me.ondeleteMenuFavouriteCompletedDelegate Is Nothing) Then
                Me.ondeleteMenuFavouriteCompletedDelegate = AddressOf Me.OndeleteMenuFavouriteCompleted
            End If
            MyBase.InvokeAsync(Me.onBegindeleteMenuFavouriteDelegate, New Object() {poMenuDTO}, Me.onEnddeleteMenuFavouriteDelegate, Me.ondeleteMenuFavouriteCompletedDelegate, userState)
        End Sub
        
        Public Function svc_getCompanyList(ByVal pcUserId As String, ByVal pcCompanyId As String) As System.Collections.Generic.List(Of MenuServiceRef.SAM_USER_COMPANYDTO) Implements MenuServiceRef.IMenuService.svc_getCompanyList
            Return MyBase.Channel.svc_getCompanyList(pcUserId, pcCompanyId)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function Beginsvc_getCompanyList(ByVal pcUserId As String, ByVal pcCompanyId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.Beginsvc_getCompanyList
            Return MyBase.Channel.Beginsvc_getCompanyList(pcUserId, pcCompanyId, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function Endsvc_getCompanyList(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of MenuServiceRef.SAM_USER_COMPANYDTO) Implements MenuServiceRef.IMenuService.Endsvc_getCompanyList
            Return MyBase.Channel.Endsvc_getCompanyList(result)
        End Function
        
        Private Function OnBeginsvc_getCompanyList(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pcUserId As String = CType(inValues(0),String)
            Dim pcCompanyId As String = CType(inValues(1),String)
            Return Me.Beginsvc_getCompanyList(pcUserId, pcCompanyId, callback, asyncState)
        End Function
        
        Private Function OnEndsvc_getCompanyList(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.Collections.Generic.List(Of MenuServiceRef.SAM_USER_COMPANYDTO) = Me.Endsvc_getCompanyList(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub Onsvc_getCompanyListCompleted(ByVal state As Object)
            If (Not (Me.svc_getCompanyListCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent svc_getCompanyListCompleted(Me, New svc_getCompanyListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub svc_getCompanyListAsync(ByVal pcUserId As String, ByVal pcCompanyId As String)
            Me.svc_getCompanyListAsync(pcUserId, pcCompanyId, Nothing)
        End Sub
        
        Public Overloads Sub svc_getCompanyListAsync(ByVal pcUserId As String, ByVal pcCompanyId As String, ByVal userState As Object)
            If (Me.onBeginsvc_getCompanyListDelegate Is Nothing) Then
                Me.onBeginsvc_getCompanyListDelegate = AddressOf Me.OnBeginsvc_getCompanyList
            End If
            If (Me.onEndsvc_getCompanyListDelegate Is Nothing) Then
                Me.onEndsvc_getCompanyListDelegate = AddressOf Me.OnEndsvc_getCompanyList
            End If
            If (Me.onsvc_getCompanyListCompletedDelegate Is Nothing) Then
                Me.onsvc_getCompanyListCompletedDelegate = AddressOf Me.Onsvc_getCompanyListCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginsvc_getCompanyListDelegate, New Object() {pcUserId, pcCompanyId}, Me.onEndsvc_getCompanyListDelegate, Me.onsvc_getCompanyListCompletedDelegate, userState)
        End Sub
        
        Public Function checkMenuFavourite(ByVal poMenuDTO As MenuServiceRef.MenuDTO) As Boolean Implements MenuServiceRef.IMenuService.checkMenuFavourite
            Return MyBase.Channel.checkMenuFavourite(poMenuDTO)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegincheckMenuFavourite(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.BegincheckMenuFavourite
            Return MyBase.Channel.BegincheckMenuFavourite(poMenuDTO, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndcheckMenuFavourite(ByVal result As System.IAsyncResult) As Boolean Implements MenuServiceRef.IMenuService.EndcheckMenuFavourite
            Return MyBase.Channel.EndcheckMenuFavourite(result)
        End Function
        
        Private Function OnBegincheckMenuFavourite(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poMenuDTO As MenuServiceRef.MenuDTO = CType(inValues(0),MenuServiceRef.MenuDTO)
            Return Me.BegincheckMenuFavourite(poMenuDTO, callback, asyncState)
        End Function
        
        Private Function OnEndcheckMenuFavourite(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Boolean = Me.EndcheckMenuFavourite(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OncheckMenuFavouriteCompleted(ByVal state As Object)
            If (Not (Me.checkMenuFavouriteCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent checkMenuFavouriteCompleted(Me, New checkMenuFavouriteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub checkMenuFavouriteAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO)
            Me.checkMenuFavouriteAsync(poMenuDTO, Nothing)
        End Sub
        
        Public Overloads Sub checkMenuFavouriteAsync(ByVal poMenuDTO As MenuServiceRef.MenuDTO, ByVal userState As Object)
            If (Me.onBegincheckMenuFavouriteDelegate Is Nothing) Then
                Me.onBegincheckMenuFavouriteDelegate = AddressOf Me.OnBegincheckMenuFavourite
            End If
            If (Me.onEndcheckMenuFavouriteDelegate Is Nothing) Then
                Me.onEndcheckMenuFavouriteDelegate = AddressOf Me.OnEndcheckMenuFavourite
            End If
            If (Me.oncheckMenuFavouriteCompletedDelegate Is Nothing) Then
                Me.oncheckMenuFavouriteCompletedDelegate = AddressOf Me.OncheckMenuFavouriteCompleted
            End If
            MyBase.InvokeAsync(Me.onBegincheckMenuFavouriteDelegate, New Object() {poMenuDTO}, Me.onEndcheckMenuFavouriteDelegate, Me.oncheckMenuFavouriteCompletedDelegate, userState)
        End Sub
        
        Public Function getSecurity() As Boolean Implements MenuServiceRef.IMenuService.getSecurity
            Return MyBase.Channel.getSecurity
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegingetSecurity(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.BegingetSecurity
            Return MyBase.Channel.BegingetSecurity(callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndgetSecurity(ByVal result As System.IAsyncResult) As Boolean Implements MenuServiceRef.IMenuService.EndgetSecurity
            Return MyBase.Channel.EndgetSecurity(result)
        End Function
        
        Private Function OnBegingetSecurity(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BegingetSecurity(callback, asyncState)
        End Function
        
        Private Function OnEndgetSecurity(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Boolean = Me.EndgetSecurity(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OngetSecurityCompleted(ByVal state As Object)
            If (Not (Me.getSecurityCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent getSecurityCompleted(Me, New getSecurityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub getSecurityAsync()
            Me.getSecurityAsync(Nothing)
        End Sub
        
        Public Overloads Sub getSecurityAsync(ByVal userState As Object)
            If (Me.onBegingetSecurityDelegate Is Nothing) Then
                Me.onBegingetSecurityDelegate = AddressOf Me.OnBegingetSecurity
            End If
            If (Me.onEndgetSecurityDelegate Is Nothing) Then
                Me.onEndgetSecurityDelegate = AddressOf Me.OnEndgetSecurity
            End If
            If (Me.ongetSecurityCompletedDelegate Is Nothing) Then
                Me.ongetSecurityCompletedDelegate = AddressOf Me.OngetSecurityCompleted
            End If
            MyBase.InvokeAsync(Me.onBegingetSecurityDelegate, Nothing, Me.onEndgetSecurityDelegate, Me.ongetSecurityCompletedDelegate, userState)
        End Sub
        
        Public Function getAccessButton(ByVal pcCompId As String, ByVal pcProgId As String) As System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO) Implements MenuServiceRef.IMenuService.getAccessButton
            Return MyBase.Channel.getAccessButton(pcCompId, pcProgId)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegingetAccessButton(ByVal pcCompId As String, ByVal pcProgId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.BegingetAccessButton
            Return MyBase.Channel.BegingetAccessButton(pcCompId, pcProgId, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndgetAccessButton(ByVal result As System.IAsyncResult) As System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO) Implements MenuServiceRef.IMenuService.EndgetAccessButton
            Return MyBase.Channel.EndgetAccessButton(result)
        End Function
        
        Private Function OnBegingetAccessButton(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pcCompId As String = CType(inValues(0),String)
            Dim pcProgId As String = CType(inValues(1),String)
            Return Me.BegingetAccessButton(pcCompId, pcProgId, callback, asyncState)
        End Function
        
        Private Function OnEndgetAccessButton(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.Collections.Generic.List(Of MenuServiceRef.MenuProgramAccessDTO) = Me.EndgetAccessButton(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OngetAccessButtonCompleted(ByVal state As Object)
            If (Not (Me.getAccessButtonCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent getAccessButtonCompleted(Me, New getAccessButtonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub getAccessButtonAsync(ByVal pcCompId As String, ByVal pcProgId As String)
            Me.getAccessButtonAsync(pcCompId, pcProgId, Nothing)
        End Sub
        
        Public Overloads Sub getAccessButtonAsync(ByVal pcCompId As String, ByVal pcProgId As String, ByVal userState As Object)
            If (Me.onBegingetAccessButtonDelegate Is Nothing) Then
                Me.onBegingetAccessButtonDelegate = AddressOf Me.OnBegingetAccessButton
            End If
            If (Me.onEndgetAccessButtonDelegate Is Nothing) Then
                Me.onEndgetAccessButtonDelegate = AddressOf Me.OnEndgetAccessButton
            End If
            If (Me.ongetAccessButtonCompletedDelegate Is Nothing) Then
                Me.ongetAccessButtonCompletedDelegate = AddressOf Me.OngetAccessButtonCompleted
            End If
            MyBase.InvokeAsync(Me.onBegingetAccessButtonDelegate, New Object() {pcCompId, pcProgId}, Me.onEndgetAccessButtonDelegate, Me.ongetAccessButtonCompletedDelegate, userState)
        End Sub
        
        Public Sub SaveHistory(ByVal pcCompId As String, ByVal pcUserId As String, ByVal pcProgId As String, ByVal pcAction As String) Implements MenuServiceRef.IMenuService.SaveHistory
            MyBase.Channel.SaveHistory(pcCompId, pcUserId, pcProgId, pcAction)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginSaveHistory(ByVal pcCompId As String, ByVal pcUserId As String, ByVal pcProgId As String, ByVal pcAction As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuServiceRef.IMenuService.BeginSaveHistory
            Return MyBase.Channel.BeginSaveHistory(pcCompId, pcUserId, pcProgId, pcAction, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndSaveHistory(ByVal result As System.IAsyncResult) Implements MenuServiceRef.IMenuService.EndSaveHistory
            MyBase.Channel.EndSaveHistory(result)
        End Sub
        
        Private Function OnBeginSaveHistory(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pcCompId As String = CType(inValues(0),String)
            Dim pcUserId As String = CType(inValues(1),String)
            Dim pcProgId As String = CType(inValues(2),String)
            Dim pcAction As String = CType(inValues(3),String)
            Return Me.BeginSaveHistory(pcCompId, pcUserId, pcProgId, pcAction, callback, asyncState)
        End Function
        
        Private Function OnEndSaveHistory(ByVal result As System.IAsyncResult) As Object()
            Me.EndSaveHistory(result)
            Return Nothing
        End Function
        
        Private Sub OnSaveHistoryCompleted(ByVal state As Object)
            If (Not (Me.SaveHistoryCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent SaveHistoryCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub SaveHistoryAsync(ByVal pcCompId As String, ByVal pcUserId As String, ByVal pcProgId As String, ByVal pcAction As String)
            Me.SaveHistoryAsync(pcCompId, pcUserId, pcProgId, pcAction, Nothing)
        End Sub
        
        Public Overloads Sub SaveHistoryAsync(ByVal pcCompId As String, ByVal pcUserId As String, ByVal pcProgId As String, ByVal pcAction As String, ByVal userState As Object)
            If (Me.onBeginSaveHistoryDelegate Is Nothing) Then
                Me.onBeginSaveHistoryDelegate = AddressOf Me.OnBeginSaveHistory
            End If
            If (Me.onEndSaveHistoryDelegate Is Nothing) Then
                Me.onEndSaveHistoryDelegate = AddressOf Me.OnEndSaveHistory
            End If
            If (Me.onSaveHistoryCompletedDelegate Is Nothing) Then
                Me.onSaveHistoryCompletedDelegate = AddressOf Me.OnSaveHistoryCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSaveHistoryDelegate, New Object() {pcCompId, pcUserId, pcProgId, pcAction}, Me.onEndSaveHistoryDelegate, Me.onSaveHistoryCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
