'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace MenuStreamingServiceRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MenuDTOnon", [Namespace]:="http://schemas.datacontract.org/2004/07/TelerikMenuBackCls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MenuDTOnon
        Inherits MenuStreamingServiceRef.R_DTOBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCOMPANY_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CMENU_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CMENU_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CPARENT_SUB_MENU_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CSUB_MENU_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CSUB_MENU_IMAGEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CSUB_MENU_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CSUB_MENU_TOOL_TIPField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CSUB_MENU_TYPEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CUSER_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ICOLUMN_INDEXField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IFAVORITE_INDEXField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IGROUP_INDEXField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ILEVELField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IROW_INDEXField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LFAVORITEField As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CCOMPANY_ID() As String
            Get
                Return Me.CCOMPANY_IDField
            End Get
            Set
                Me.CCOMPANY_IDField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CMENU_ID() As String
            Get
                Return Me.CMENU_IDField
            End Get
            Set
                Me.CMENU_IDField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CMENU_NAME() As String
            Get
                Return Me.CMENU_NAMEField
            End Get
            Set
                Me.CMENU_NAMEField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CPARENT_SUB_MENU_ID() As String
            Get
                Return Me.CPARENT_SUB_MENU_IDField
            End Get
            Set
                Me.CPARENT_SUB_MENU_IDField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CSUB_MENU_ID() As String
            Get
                Return Me.CSUB_MENU_IDField
            End Get
            Set
                Me.CSUB_MENU_IDField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CSUB_MENU_IMAGE() As String
            Get
                Return Me.CSUB_MENU_IMAGEField
            End Get
            Set
                Me.CSUB_MENU_IMAGEField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CSUB_MENU_NAME() As String
            Get
                Return Me.CSUB_MENU_NAMEField
            End Get
            Set
                Me.CSUB_MENU_NAMEField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CSUB_MENU_TOOL_TIP() As String
            Get
                Return Me.CSUB_MENU_TOOL_TIPField
            End Get
            Set
                Me.CSUB_MENU_TOOL_TIPField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CSUB_MENU_TYPE() As String
            Get
                Return Me.CSUB_MENU_TYPEField
            End Get
            Set
                Me.CSUB_MENU_TYPEField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CUSER_ID() As String
            Get
                Return Me.CUSER_IDField
            End Get
            Set
                Me.CUSER_IDField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ICOLUMN_INDEX() As System.Nullable(Of Integer)
            Get
                Return Me.ICOLUMN_INDEXField
            End Get
            Set
                Me.ICOLUMN_INDEXField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IFAVORITE_INDEX() As System.Nullable(Of Integer)
            Get
                Return Me.IFAVORITE_INDEXField
            End Get
            Set
                Me.IFAVORITE_INDEXField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IGROUP_INDEX() As System.Nullable(Of Integer)
            Get
                Return Me.IGROUP_INDEXField
            End Get
            Set
                Me.IGROUP_INDEXField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ILEVEL() As Integer
            Get
                Return Me.ILEVELField
            End Get
            Set
                Me.ILEVELField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IROW_INDEX() As System.Nullable(Of Integer)
            Get
                Return Me.IROW_INDEXField
            End Get
            Set
                Me.IROW_INDEXField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LFAVORITE() As Boolean
            Get
                Return Me.LFAVORITEField
            End Get
            Set
                Me.LFAVORITEField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="R_DTOBase", [Namespace]:="http://schemas.datacontract.org/2004/07/R_BackEnd"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(MenuStreamingServiceRef.MenuDTOnon))>  _
    Partial Public Class R_DTOBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="MenuStreamingServiceRef.IMenuStreamingService")>  _
    Public Interface IMenuStreamingService
        
        <System.ServiceModel.OperationContractAttribute(Action:="getMenu", ReplyAction:="getMenu"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuStreamingService/getMenuR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function getMenu() As System.ServiceModel.Channels.Message
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="getMenu", ReplyAction:="getMenu")>  _
        Function BegingetMenu(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndgetMenu(ByVal result As System.IAsyncResult) As System.ServiceModel.Channels.Message
        
        <System.ServiceModel.OperationContractAttribute(Action:="getMenuAccess", ReplyAction:="getMenuAccess"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuStreamingService/getMenuAccessR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function getMenuAccess() As System.ServiceModel.Channels.Message
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="getMenuAccess", ReplyAction:="getMenuAccess")>  _
        Function BegingetMenuAccess(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndgetMenuAccess(ByVal result As System.IAsyncResult) As System.ServiceModel.Channels.Message
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IMenuStreamingService/Dummy", ReplyAction:="http://tempuri.org/IMenuStreamingService/DummyResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/IMenuStreamingService/DummyR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub Dummy(ByVal poPar As System.Collections.Generic.List(Of MenuStreamingServiceRef.MenuDTOnon))
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/IMenuStreamingService/Dummy", ReplyAction:="http://tempuri.org/IMenuStreamingService/DummyResponse")>  _
        Function BeginDummy(ByVal poPar As System.Collections.Generic.List(Of MenuStreamingServiceRef.MenuDTOnon), ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndDummy(ByVal result As System.IAsyncResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IMenuStreamingServiceChannel
        Inherits MenuStreamingServiceRef.IMenuStreamingService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class getMenuCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.ServiceModel.Channels.Message
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.ServiceModel.Channels.Message)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class getMenuAccessCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.ServiceModel.Channels.Message
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.ServiceModel.Channels.Message)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MenuStreamingServiceClient
        Inherits System.ServiceModel.ClientBase(Of MenuStreamingServiceRef.IMenuStreamingService)
        Implements MenuStreamingServiceRef.IMenuStreamingService
        
        Private onBegingetMenuDelegate As BeginOperationDelegate
        
        Private onEndgetMenuDelegate As EndOperationDelegate
        
        Private ongetMenuCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBegingetMenuAccessDelegate As BeginOperationDelegate
        
        Private onEndgetMenuAccessDelegate As EndOperationDelegate
        
        Private ongetMenuAccessCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginDummyDelegate As BeginOperationDelegate
        
        Private onEndDummyDelegate As EndOperationDelegate
        
        Private onDummyCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event getMenuCompleted As System.EventHandler(Of getMenuCompletedEventArgs)
        
        Public Event getMenuAccessCompleted As System.EventHandler(Of getMenuAccessCompletedEventArgs)
        
        Public Event DummyCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Function getMenu() As System.ServiceModel.Channels.Message Implements MenuStreamingServiceRef.IMenuStreamingService.getMenu
            Return MyBase.Channel.getMenu
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegingetMenu(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuStreamingServiceRef.IMenuStreamingService.BegingetMenu
            Return MyBase.Channel.BegingetMenu(callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndgetMenu(ByVal result As System.IAsyncResult) As System.ServiceModel.Channels.Message Implements MenuStreamingServiceRef.IMenuStreamingService.EndgetMenu
            Return MyBase.Channel.EndgetMenu(result)
        End Function
        
        Private Function OnBegingetMenu(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BegingetMenu(callback, asyncState)
        End Function
        
        Private Function OnEndgetMenu(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.ServiceModel.Channels.Message = Me.EndgetMenu(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OngetMenuCompleted(ByVal state As Object)
            If (Not (Me.getMenuCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent getMenuCompleted(Me, New getMenuCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub getMenuAsync()
            Me.getMenuAsync(Nothing)
        End Sub
        
        Public Overloads Sub getMenuAsync(ByVal userState As Object)
            If (Me.onBegingetMenuDelegate Is Nothing) Then
                Me.onBegingetMenuDelegate = AddressOf Me.OnBegingetMenu
            End If
            If (Me.onEndgetMenuDelegate Is Nothing) Then
                Me.onEndgetMenuDelegate = AddressOf Me.OnEndgetMenu
            End If
            If (Me.ongetMenuCompletedDelegate Is Nothing) Then
                Me.ongetMenuCompletedDelegate = AddressOf Me.OngetMenuCompleted
            End If
            MyBase.InvokeAsync(Me.onBegingetMenuDelegate, Nothing, Me.onEndgetMenuDelegate, Me.ongetMenuCompletedDelegate, userState)
        End Sub
        
        Public Function getMenuAccess() As System.ServiceModel.Channels.Message Implements MenuStreamingServiceRef.IMenuStreamingService.getMenuAccess
            Return MyBase.Channel.getMenuAccess
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegingetMenuAccess(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuStreamingServiceRef.IMenuStreamingService.BegingetMenuAccess
            Return MyBase.Channel.BegingetMenuAccess(callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndgetMenuAccess(ByVal result As System.IAsyncResult) As System.ServiceModel.Channels.Message Implements MenuStreamingServiceRef.IMenuStreamingService.EndgetMenuAccess
            Return MyBase.Channel.EndgetMenuAccess(result)
        End Function
        
        Private Function OnBegingetMenuAccess(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BegingetMenuAccess(callback, asyncState)
        End Function
        
        Private Function OnEndgetMenuAccess(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.ServiceModel.Channels.Message = Me.EndgetMenuAccess(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OngetMenuAccessCompleted(ByVal state As Object)
            If (Not (Me.getMenuAccessCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent getMenuAccessCompleted(Me, New getMenuAccessCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub getMenuAccessAsync()
            Me.getMenuAccessAsync(Nothing)
        End Sub
        
        Public Overloads Sub getMenuAccessAsync(ByVal userState As Object)
            If (Me.onBegingetMenuAccessDelegate Is Nothing) Then
                Me.onBegingetMenuAccessDelegate = AddressOf Me.OnBegingetMenuAccess
            End If
            If (Me.onEndgetMenuAccessDelegate Is Nothing) Then
                Me.onEndgetMenuAccessDelegate = AddressOf Me.OnEndgetMenuAccess
            End If
            If (Me.ongetMenuAccessCompletedDelegate Is Nothing) Then
                Me.ongetMenuAccessCompletedDelegate = AddressOf Me.OngetMenuAccessCompleted
            End If
            MyBase.InvokeAsync(Me.onBegingetMenuAccessDelegate, Nothing, Me.onEndgetMenuAccessDelegate, Me.ongetMenuAccessCompletedDelegate, userState)
        End Sub
        
        Public Sub Dummy(ByVal poPar As System.Collections.Generic.List(Of MenuStreamingServiceRef.MenuDTOnon)) Implements MenuStreamingServiceRef.IMenuStreamingService.Dummy
            MyBase.Channel.Dummy(poPar)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginDummy(ByVal poPar As System.Collections.Generic.List(Of MenuStreamingServiceRef.MenuDTOnon), ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements MenuStreamingServiceRef.IMenuStreamingService.BeginDummy
            Return MyBase.Channel.BeginDummy(poPar, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndDummy(ByVal result As System.IAsyncResult) Implements MenuStreamingServiceRef.IMenuStreamingService.EndDummy
            MyBase.Channel.EndDummy(result)
        End Sub
        
        Private Function OnBeginDummy(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poPar As System.Collections.Generic.List(Of MenuStreamingServiceRef.MenuDTOnon) = CType(inValues(0),System.Collections.Generic.List(Of MenuStreamingServiceRef.MenuDTOnon))
            Return Me.BeginDummy(poPar, callback, asyncState)
        End Function
        
        Private Function OnEndDummy(ByVal result As System.IAsyncResult) As Object()
            Me.EndDummy(result)
            Return Nothing
        End Function
        
        Private Sub OnDummyCompleted(ByVal state As Object)
            If (Not (Me.DummyCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent DummyCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub DummyAsync(ByVal poPar As System.Collections.Generic.List(Of MenuStreamingServiceRef.MenuDTOnon))
            Me.DummyAsync(poPar, Nothing)
        End Sub
        
        Public Overloads Sub DummyAsync(ByVal poPar As System.Collections.Generic.List(Of MenuStreamingServiceRef.MenuDTOnon), ByVal userState As Object)
            If (Me.onBeginDummyDelegate Is Nothing) Then
                Me.onBeginDummyDelegate = AddressOf Me.OnBeginDummy
            End If
            If (Me.onEndDummyDelegate Is Nothing) Then
                Me.onEndDummyDelegate = AddressOf Me.OnEndDummy
            End If
            If (Me.onDummyCompletedDelegate Is Nothing) Then
                Me.onDummyCompletedDelegate = AddressOf Me.OnDummyCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginDummyDelegate, New Object() {poPar}, Me.onEndDummyDelegate, Me.onDummyCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
