'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace LoginServiceRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="R_DTOBase", [Namespace]:="http://schemas.datacontract.org/2004/07/R_BackEnd"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(LoginServiceRef.LoginDTO))>  _
    Partial Public Class R_DTOBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LoginDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/TelerikMenuBackCls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LoginDTO
        Inherits LoginServiceRef.R_DTOBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCOMPANY_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCOMPANY_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCULTURE_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CDATE_LONG_FORMATField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CDATE_SHORT_FORMATField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CLICENSE_MODEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CNUMBER_FORMATField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CREPORT_CULTUREField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CROUNDING_METHODField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CTIME_LONG_FORMATField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CTIME_SHORT_FORMATField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CUSER_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CUSER_NAMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CUSER_PASSWORDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DLAST_UPDATE_PSWDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDECIMAL_PLACESField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IROUNDING_PLACESField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LENABLE_SAVE_CONFIRMATIONField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NLICENSEEField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CCOMPANY_ID() As String
            Get
                Return Me.CCOMPANY_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CCOMPANY_IDField, value) <> true) Then
                    Me.CCOMPANY_IDField = value
                    Me.RaisePropertyChanged("CCOMPANY_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CCOMPANY_NAME() As String
            Get
                Return Me.CCOMPANY_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CCOMPANY_NAMEField, value) <> true) Then
                    Me.CCOMPANY_NAMEField = value
                    Me.RaisePropertyChanged("CCOMPANY_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CCULTURE_ID() As String
            Get
                Return Me.CCULTURE_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CCULTURE_IDField, value) <> true) Then
                    Me.CCULTURE_IDField = value
                    Me.RaisePropertyChanged("CCULTURE_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CDATE_LONG_FORMAT() As String
            Get
                Return Me.CDATE_LONG_FORMATField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CDATE_LONG_FORMATField, value) <> true) Then
                    Me.CDATE_LONG_FORMATField = value
                    Me.RaisePropertyChanged("CDATE_LONG_FORMAT")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CDATE_SHORT_FORMAT() As String
            Get
                Return Me.CDATE_SHORT_FORMATField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CDATE_SHORT_FORMATField, value) <> true) Then
                    Me.CDATE_SHORT_FORMATField = value
                    Me.RaisePropertyChanged("CDATE_SHORT_FORMAT")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CLICENSE_MODE() As String
            Get
                Return Me.CLICENSE_MODEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CLICENSE_MODEField, value) <> true) Then
                    Me.CLICENSE_MODEField = value
                    Me.RaisePropertyChanged("CLICENSE_MODE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CNUMBER_FORMAT() As String
            Get
                Return Me.CNUMBER_FORMATField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CNUMBER_FORMATField, value) <> true) Then
                    Me.CNUMBER_FORMATField = value
                    Me.RaisePropertyChanged("CNUMBER_FORMAT")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CREPORT_CULTURE() As String
            Get
                Return Me.CREPORT_CULTUREField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CREPORT_CULTUREField, value) <> true) Then
                    Me.CREPORT_CULTUREField = value
                    Me.RaisePropertyChanged("CREPORT_CULTURE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CROUNDING_METHOD() As String
            Get
                Return Me.CROUNDING_METHODField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CROUNDING_METHODField, value) <> true) Then
                    Me.CROUNDING_METHODField = value
                    Me.RaisePropertyChanged("CROUNDING_METHOD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CTIME_LONG_FORMAT() As String
            Get
                Return Me.CTIME_LONG_FORMATField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CTIME_LONG_FORMATField, value) <> true) Then
                    Me.CTIME_LONG_FORMATField = value
                    Me.RaisePropertyChanged("CTIME_LONG_FORMAT")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CTIME_SHORT_FORMAT() As String
            Get
                Return Me.CTIME_SHORT_FORMATField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CTIME_SHORT_FORMATField, value) <> true) Then
                    Me.CTIME_SHORT_FORMATField = value
                    Me.RaisePropertyChanged("CTIME_SHORT_FORMAT")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CUSER_ID() As String
            Get
                Return Me.CUSER_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CUSER_IDField, value) <> true) Then
                    Me.CUSER_IDField = value
                    Me.RaisePropertyChanged("CUSER_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CUSER_NAME() As String
            Get
                Return Me.CUSER_NAMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CUSER_NAMEField, value) <> true) Then
                    Me.CUSER_NAMEField = value
                    Me.RaisePropertyChanged("CUSER_NAME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CUSER_PASSWORD() As String
            Get
                Return Me.CUSER_PASSWORDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CUSER_PASSWORDField, value) <> true) Then
                    Me.CUSER_PASSWORDField = value
                    Me.RaisePropertyChanged("CUSER_PASSWORD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DLAST_UPDATE_PSWD() As String
            Get
                Return Me.DLAST_UPDATE_PSWDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DLAST_UPDATE_PSWDField, value) <> true) Then
                    Me.DLAST_UPDATE_PSWDField = value
                    Me.RaisePropertyChanged("DLAST_UPDATE_PSWD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IDECIMAL_PLACES() As Integer
            Get
                Return Me.IDECIMAL_PLACESField
            End Get
            Set
                If (Me.IDECIMAL_PLACESField.Equals(value) <> true) Then
                    Me.IDECIMAL_PLACESField = value
                    Me.RaisePropertyChanged("IDECIMAL_PLACES")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IROUNDING_PLACES() As Integer
            Get
                Return Me.IROUNDING_PLACESField
            End Get
            Set
                If (Me.IROUNDING_PLACESField.Equals(value) <> true) Then
                    Me.IROUNDING_PLACESField = value
                    Me.RaisePropertyChanged("IROUNDING_PLACES")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LENABLE_SAVE_CONFIRMATION() As Boolean
            Get
                Return Me.LENABLE_SAVE_CONFIRMATIONField
            End Get
            Set
                If (Me.LENABLE_SAVE_CONFIRMATIONField.Equals(value) <> true) Then
                    Me.LENABLE_SAVE_CONFIRMATIONField = value
                    Me.RaisePropertyChanged("LENABLE_SAVE_CONFIRMATION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NLICENSEE() As Integer
            Get
                Return Me.NLICENSEEField
            End Get
            Set
                If (Me.NLICENSEEField.Equals(value) <> true) Then
                    Me.NLICENSEEField = value
                    Me.RaisePropertyChanged("NLICENSEE")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SAM_USER_COMPANYDTO", [Namespace]:="http://schemas.datacontract.org/2004/07/TelerikMenuBackCls"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SAM_USER_COMPANYDTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCOMPANY_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CUSER_IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LCAN_BROADCASTField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CCOMPANY_ID() As String
            Get
                Return Me.CCOMPANY_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CCOMPANY_IDField, value) <> true) Then
                    Me.CCOMPANY_IDField = value
                    Me.RaisePropertyChanged("CCOMPANY_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CUSER_ID() As String
            Get
                Return Me.CUSER_IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CUSER_IDField, value) <> true) Then
                    Me.CUSER_IDField = value
                    Me.RaisePropertyChanged("CUSER_ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LCAN_BROADCAST() As Boolean
            Get
                Return Me.LCAN_BROADCASTField
            End Get
            Set
                If (Me.LCAN_BROADCASTField.Equals(value) <> true) Then
                    Me.LCAN_BROADCASTField = value
                    Me.RaisePropertyChanged("LCAN_BROADCAST")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="LoginServiceRef.ILoginService")>  _
    Public Interface ILoginService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILoginService/Svc_R_UserLocking", ReplyAction:="http://tempuri.org/ILoginService/Svc_R_UserLockingResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/ILoginService/Svc_R_UserLockingR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub Svc_R_UserLocking(ByVal poParameter As LoginServiceRef.LoginDTO)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ILoginService/Svc_R_UserLocking", ReplyAction:="http://tempuri.org/ILoginService/Svc_R_UserLockingResponse")>  _
        Function BeginSvc_R_UserLocking(ByVal poParameter As LoginServiceRef.LoginDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndSvc_R_UserLocking(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILoginService/Svc_R_UserLockingCompany", ReplyAction:="http://tempuri.org/ILoginService/Svc_R_UserLockingCompanyResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/ILoginService/Svc_R_UserLockingCompanyR_ServiceExceptionsFault"& _ 
            "", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub Svc_R_UserLockingCompany(ByVal pcCurrentCompanyId As String, ByVal pcNewCompanyId As String, ByVal pcUserId As String)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ILoginService/Svc_R_UserLockingCompany", ReplyAction:="http://tempuri.org/ILoginService/Svc_R_UserLockingCompanyResponse")>  _
        Function BeginSvc_R_UserLockingCompany(ByVal pcCurrentCompanyId As String, ByVal pcNewCompanyId As String, ByVal pcUserId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndSvc_R_UserLockingCompany(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILoginService/Svc_R_UserLockingFlush", ReplyAction:="http://tempuri.org/ILoginService/Svc_R_UserLockingFlushResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/ILoginService/Svc_R_UserLockingFlushR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub Svc_R_UserLockingFlush(ByVal pcCurrentCompanyId As String, ByVal pcUserId As String)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ILoginService/Svc_R_UserLockingFlush", ReplyAction:="http://tempuri.org/ILoginService/Svc_R_UserLockingFlushResponse")>  _
        Function BeginSvc_R_UserLockingFlush(ByVal pcCurrentCompanyId As String, ByVal pcUserId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndSvc_R_UserLockingFlush(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILoginService/Logon", ReplyAction:="http://tempuri.org/ILoginService/LogonResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/ILoginService/LogonR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function Logon(ByVal poParameter As LoginServiceRef.LoginDTO) As LoginServiceRef.LoginDTO
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ILoginService/Logon", ReplyAction:="http://tempuri.org/ILoginService/LogonResponse")>  _
        Function BeginLogon(ByVal poParameter As LoginServiceRef.LoginDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndLogon(ByVal result As System.IAsyncResult) As LoginServiceRef.LoginDTO
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILoginService/SetKey", ReplyAction:="http://tempuri.org/ILoginService/SetKeyResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/ILoginService/SetKeyR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function SetKey(ByVal pcKey As String) As String
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ILoginService/SetKey", ReplyAction:="http://tempuri.org/ILoginService/SetKeyResponse")>  _
        Function BeginSetKey(ByVal pcKey As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndSetKey(ByVal result As System.IAsyncResult) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILoginService/svc_getUserCompanyBroadcast", ReplyAction:="http://tempuri.org/ILoginService/svc_getUserCompanyBroadcastResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/ILoginService/svc_getUserCompanyBroadcastR_ServiceExceptionsFa"& _ 
            "ult", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function svc_getUserCompanyBroadcast(ByVal poParameter As LoginServiceRef.SAM_USER_COMPANYDTO) As LoginServiceRef.SAM_USER_COMPANYDTO
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ILoginService/svc_getUserCompanyBroadcast", ReplyAction:="http://tempuri.org/ILoginService/svc_getUserCompanyBroadcastResponse")>  _
        Function Beginsvc_getUserCompanyBroadcast(ByVal poParameter As LoginServiceRef.SAM_USER_COMPANYDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function Endsvc_getUserCompanyBroadcast(ByVal result As System.IAsyncResult) As LoginServiceRef.SAM_USER_COMPANYDTO
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILoginService/svc_getCompanyAndUserName", ReplyAction:="http://tempuri.org/ILoginService/svc_getCompanyAndUserNameResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/ILoginService/svc_getCompanyAndUserNameR_ServiceExceptionsFaul"& _ 
            "t", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function svc_getCompanyAndUserName(ByVal poParameter As LoginServiceRef.LoginDTO) As LoginServiceRef.LoginDTO
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ILoginService/svc_getCompanyAndUserName", ReplyAction:="http://tempuri.org/ILoginService/svc_getCompanyAndUserNameResponse")>  _
        Function Beginsvc_getCompanyAndUserName(ByVal poParameter As LoginServiceRef.LoginDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function Endsvc_getCompanyAndUserName(ByVal result As System.IAsyncResult) As LoginServiceRef.LoginDTO
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILoginService/getLastUpdate", ReplyAction:="http://tempuri.org/ILoginService/getLastUpdateResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/ILoginService/getLastUpdateR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Function getLastUpdate(ByVal poParameter As LoginServiceRef.LoginDTO) As System.Nullable(Of Date)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ILoginService/getLastUpdate", ReplyAction:="http://tempuri.org/ILoginService/getLastUpdateResponse")>  _
        Function BegingetLastUpdate(ByVal poParameter As LoginServiceRef.LoginDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndgetLastUpdate(ByVal result As System.IAsyncResult) As System.Nullable(Of Date)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILoginService/doFlushData", ReplyAction:="http://tempuri.org/ILoginService/doFlushDataResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(R_Common.R_ServiceExceptions), Action:="http://tempuri.org/ILoginService/doFlushDataR_ServiceExceptionsFault", Name:="R_ServiceExceptions", [Namespace]:="http://schemas.datacontract.org/2004/07/R_Common")>  _
        Sub doFlushData(ByVal pcUserId As String, ByVal pcCompanyId As String)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ILoginService/doFlushData", ReplyAction:="http://tempuri.org/ILoginService/doFlushDataResponse")>  _
        Function BegindoFlushData(ByVal pcUserId As String, ByVal pcCompanyId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EnddoFlushData(ByVal result As System.IAsyncResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ILoginServiceChannel
        Inherits LoginServiceRef.ILoginService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LogonCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As LoginServiceRef.LoginDTO
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),LoginServiceRef.LoginDTO)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SetKeyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class svc_getUserCompanyBroadcastCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As LoginServiceRef.SAM_USER_COMPANYDTO
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),LoginServiceRef.SAM_USER_COMPANYDTO)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class svc_getCompanyAndUserNameCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As LoginServiceRef.LoginDTO
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),LoginServiceRef.LoginDTO)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class getLastUpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As System.Nullable(Of Date)
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Nullable(Of Date))
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LoginServiceClient
        Inherits System.ServiceModel.ClientBase(Of LoginServiceRef.ILoginService)
        Implements LoginServiceRef.ILoginService
        
        Private onBeginSvc_R_UserLockingDelegate As BeginOperationDelegate
        
        Private onEndSvc_R_UserLockingDelegate As EndOperationDelegate
        
        Private onSvc_R_UserLockingCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginSvc_R_UserLockingCompanyDelegate As BeginOperationDelegate
        
        Private onEndSvc_R_UserLockingCompanyDelegate As EndOperationDelegate
        
        Private onSvc_R_UserLockingCompanyCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginSvc_R_UserLockingFlushDelegate As BeginOperationDelegate
        
        Private onEndSvc_R_UserLockingFlushDelegate As EndOperationDelegate
        
        Private onSvc_R_UserLockingFlushCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginLogonDelegate As BeginOperationDelegate
        
        Private onEndLogonDelegate As EndOperationDelegate
        
        Private onLogonCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginSetKeyDelegate As BeginOperationDelegate
        
        Private onEndSetKeyDelegate As EndOperationDelegate
        
        Private onSetKeyCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginsvc_getUserCompanyBroadcastDelegate As BeginOperationDelegate
        
        Private onEndsvc_getUserCompanyBroadcastDelegate As EndOperationDelegate
        
        Private onsvc_getUserCompanyBroadcastCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginsvc_getCompanyAndUserNameDelegate As BeginOperationDelegate
        
        Private onEndsvc_getCompanyAndUserNameDelegate As EndOperationDelegate
        
        Private onsvc_getCompanyAndUserNameCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBegingetLastUpdateDelegate As BeginOperationDelegate
        
        Private onEndgetLastUpdateDelegate As EndOperationDelegate
        
        Private ongetLastUpdateCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBegindoFlushDataDelegate As BeginOperationDelegate
        
        Private onEnddoFlushDataDelegate As EndOperationDelegate
        
        Private ondoFlushDataCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event Svc_R_UserLockingCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event Svc_R_UserLockingCompanyCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event Svc_R_UserLockingFlushCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event LogonCompleted As System.EventHandler(Of LogonCompletedEventArgs)
        
        Public Event SetKeyCompleted As System.EventHandler(Of SetKeyCompletedEventArgs)
        
        Public Event svc_getUserCompanyBroadcastCompleted As System.EventHandler(Of svc_getUserCompanyBroadcastCompletedEventArgs)
        
        Public Event svc_getCompanyAndUserNameCompleted As System.EventHandler(Of svc_getCompanyAndUserNameCompletedEventArgs)
        
        Public Event getLastUpdateCompleted As System.EventHandler(Of getLastUpdateCompletedEventArgs)
        
        Public Event doFlushDataCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Sub Svc_R_UserLocking(ByVal poParameter As LoginServiceRef.LoginDTO) Implements LoginServiceRef.ILoginService.Svc_R_UserLocking
            MyBase.Channel.Svc_R_UserLocking(poParameter)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginSvc_R_UserLocking(ByVal poParameter As LoginServiceRef.LoginDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements LoginServiceRef.ILoginService.BeginSvc_R_UserLocking
            Return MyBase.Channel.BeginSvc_R_UserLocking(poParameter, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndSvc_R_UserLocking(ByVal result As System.IAsyncResult) Implements LoginServiceRef.ILoginService.EndSvc_R_UserLocking
            MyBase.Channel.EndSvc_R_UserLocking(result)
        End Sub
        
        Private Function OnBeginSvc_R_UserLocking(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poParameter As LoginServiceRef.LoginDTO = CType(inValues(0),LoginServiceRef.LoginDTO)
            Return Me.BeginSvc_R_UserLocking(poParameter, callback, asyncState)
        End Function
        
        Private Function OnEndSvc_R_UserLocking(ByVal result As System.IAsyncResult) As Object()
            Me.EndSvc_R_UserLocking(result)
            Return Nothing
        End Function
        
        Private Sub OnSvc_R_UserLockingCompleted(ByVal state As Object)
            If (Not (Me.Svc_R_UserLockingCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent Svc_R_UserLockingCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub Svc_R_UserLockingAsync(ByVal poParameter As LoginServiceRef.LoginDTO)
            Me.Svc_R_UserLockingAsync(poParameter, Nothing)
        End Sub
        
        Public Overloads Sub Svc_R_UserLockingAsync(ByVal poParameter As LoginServiceRef.LoginDTO, ByVal userState As Object)
            If (Me.onBeginSvc_R_UserLockingDelegate Is Nothing) Then
                Me.onBeginSvc_R_UserLockingDelegate = AddressOf Me.OnBeginSvc_R_UserLocking
            End If
            If (Me.onEndSvc_R_UserLockingDelegate Is Nothing) Then
                Me.onEndSvc_R_UserLockingDelegate = AddressOf Me.OnEndSvc_R_UserLocking
            End If
            If (Me.onSvc_R_UserLockingCompletedDelegate Is Nothing) Then
                Me.onSvc_R_UserLockingCompletedDelegate = AddressOf Me.OnSvc_R_UserLockingCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSvc_R_UserLockingDelegate, New Object() {poParameter}, Me.onEndSvc_R_UserLockingDelegate, Me.onSvc_R_UserLockingCompletedDelegate, userState)
        End Sub
        
        Public Sub Svc_R_UserLockingCompany(ByVal pcCurrentCompanyId As String, ByVal pcNewCompanyId As String, ByVal pcUserId As String) Implements LoginServiceRef.ILoginService.Svc_R_UserLockingCompany
            MyBase.Channel.Svc_R_UserLockingCompany(pcCurrentCompanyId, pcNewCompanyId, pcUserId)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginSvc_R_UserLockingCompany(ByVal pcCurrentCompanyId As String, ByVal pcNewCompanyId As String, ByVal pcUserId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements LoginServiceRef.ILoginService.BeginSvc_R_UserLockingCompany
            Return MyBase.Channel.BeginSvc_R_UserLockingCompany(pcCurrentCompanyId, pcNewCompanyId, pcUserId, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndSvc_R_UserLockingCompany(ByVal result As System.IAsyncResult) Implements LoginServiceRef.ILoginService.EndSvc_R_UserLockingCompany
            MyBase.Channel.EndSvc_R_UserLockingCompany(result)
        End Sub
        
        Private Function OnBeginSvc_R_UserLockingCompany(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pcCurrentCompanyId As String = CType(inValues(0),String)
            Dim pcNewCompanyId As String = CType(inValues(1),String)
            Dim pcUserId As String = CType(inValues(2),String)
            Return Me.BeginSvc_R_UserLockingCompany(pcCurrentCompanyId, pcNewCompanyId, pcUserId, callback, asyncState)
        End Function
        
        Private Function OnEndSvc_R_UserLockingCompany(ByVal result As System.IAsyncResult) As Object()
            Me.EndSvc_R_UserLockingCompany(result)
            Return Nothing
        End Function
        
        Private Sub OnSvc_R_UserLockingCompanyCompleted(ByVal state As Object)
            If (Not (Me.Svc_R_UserLockingCompanyCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent Svc_R_UserLockingCompanyCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub Svc_R_UserLockingCompanyAsync(ByVal pcCurrentCompanyId As String, ByVal pcNewCompanyId As String, ByVal pcUserId As String)
            Me.Svc_R_UserLockingCompanyAsync(pcCurrentCompanyId, pcNewCompanyId, pcUserId, Nothing)
        End Sub
        
        Public Overloads Sub Svc_R_UserLockingCompanyAsync(ByVal pcCurrentCompanyId As String, ByVal pcNewCompanyId As String, ByVal pcUserId As String, ByVal userState As Object)
            If (Me.onBeginSvc_R_UserLockingCompanyDelegate Is Nothing) Then
                Me.onBeginSvc_R_UserLockingCompanyDelegate = AddressOf Me.OnBeginSvc_R_UserLockingCompany
            End If
            If (Me.onEndSvc_R_UserLockingCompanyDelegate Is Nothing) Then
                Me.onEndSvc_R_UserLockingCompanyDelegate = AddressOf Me.OnEndSvc_R_UserLockingCompany
            End If
            If (Me.onSvc_R_UserLockingCompanyCompletedDelegate Is Nothing) Then
                Me.onSvc_R_UserLockingCompanyCompletedDelegate = AddressOf Me.OnSvc_R_UserLockingCompanyCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSvc_R_UserLockingCompanyDelegate, New Object() {pcCurrentCompanyId, pcNewCompanyId, pcUserId}, Me.onEndSvc_R_UserLockingCompanyDelegate, Me.onSvc_R_UserLockingCompanyCompletedDelegate, userState)
        End Sub
        
        Public Sub Svc_R_UserLockingFlush(ByVal pcCurrentCompanyId As String, ByVal pcUserId As String) Implements LoginServiceRef.ILoginService.Svc_R_UserLockingFlush
            MyBase.Channel.Svc_R_UserLockingFlush(pcCurrentCompanyId, pcUserId)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginSvc_R_UserLockingFlush(ByVal pcCurrentCompanyId As String, ByVal pcUserId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements LoginServiceRef.ILoginService.BeginSvc_R_UserLockingFlush
            Return MyBase.Channel.BeginSvc_R_UserLockingFlush(pcCurrentCompanyId, pcUserId, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EndSvc_R_UserLockingFlush(ByVal result As System.IAsyncResult) Implements LoginServiceRef.ILoginService.EndSvc_R_UserLockingFlush
            MyBase.Channel.EndSvc_R_UserLockingFlush(result)
        End Sub
        
        Private Function OnBeginSvc_R_UserLockingFlush(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pcCurrentCompanyId As String = CType(inValues(0),String)
            Dim pcUserId As String = CType(inValues(1),String)
            Return Me.BeginSvc_R_UserLockingFlush(pcCurrentCompanyId, pcUserId, callback, asyncState)
        End Function
        
        Private Function OnEndSvc_R_UserLockingFlush(ByVal result As System.IAsyncResult) As Object()
            Me.EndSvc_R_UserLockingFlush(result)
            Return Nothing
        End Function
        
        Private Sub OnSvc_R_UserLockingFlushCompleted(ByVal state As Object)
            If (Not (Me.Svc_R_UserLockingFlushCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent Svc_R_UserLockingFlushCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub Svc_R_UserLockingFlushAsync(ByVal pcCurrentCompanyId As String, ByVal pcUserId As String)
            Me.Svc_R_UserLockingFlushAsync(pcCurrentCompanyId, pcUserId, Nothing)
        End Sub
        
        Public Overloads Sub Svc_R_UserLockingFlushAsync(ByVal pcCurrentCompanyId As String, ByVal pcUserId As String, ByVal userState As Object)
            If (Me.onBeginSvc_R_UserLockingFlushDelegate Is Nothing) Then
                Me.onBeginSvc_R_UserLockingFlushDelegate = AddressOf Me.OnBeginSvc_R_UserLockingFlush
            End If
            If (Me.onEndSvc_R_UserLockingFlushDelegate Is Nothing) Then
                Me.onEndSvc_R_UserLockingFlushDelegate = AddressOf Me.OnEndSvc_R_UserLockingFlush
            End If
            If (Me.onSvc_R_UserLockingFlushCompletedDelegate Is Nothing) Then
                Me.onSvc_R_UserLockingFlushCompletedDelegate = AddressOf Me.OnSvc_R_UserLockingFlushCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSvc_R_UserLockingFlushDelegate, New Object() {pcCurrentCompanyId, pcUserId}, Me.onEndSvc_R_UserLockingFlushDelegate, Me.onSvc_R_UserLockingFlushCompletedDelegate, userState)
        End Sub
        
        Public Function Logon(ByVal poParameter As LoginServiceRef.LoginDTO) As LoginServiceRef.LoginDTO Implements LoginServiceRef.ILoginService.Logon
            Return MyBase.Channel.Logon(poParameter)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginLogon(ByVal poParameter As LoginServiceRef.LoginDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements LoginServiceRef.ILoginService.BeginLogon
            Return MyBase.Channel.BeginLogon(poParameter, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndLogon(ByVal result As System.IAsyncResult) As LoginServiceRef.LoginDTO Implements LoginServiceRef.ILoginService.EndLogon
            Return MyBase.Channel.EndLogon(result)
        End Function
        
        Private Function OnBeginLogon(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poParameter As LoginServiceRef.LoginDTO = CType(inValues(0),LoginServiceRef.LoginDTO)
            Return Me.BeginLogon(poParameter, callback, asyncState)
        End Function
        
        Private Function OnEndLogon(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As LoginServiceRef.LoginDTO = Me.EndLogon(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnLogonCompleted(ByVal state As Object)
            If (Not (Me.LogonCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent LogonCompleted(Me, New LogonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub LogonAsync(ByVal poParameter As LoginServiceRef.LoginDTO)
            Me.LogonAsync(poParameter, Nothing)
        End Sub
        
        Public Overloads Sub LogonAsync(ByVal poParameter As LoginServiceRef.LoginDTO, ByVal userState As Object)
            If (Me.onBeginLogonDelegate Is Nothing) Then
                Me.onBeginLogonDelegate = AddressOf Me.OnBeginLogon
            End If
            If (Me.onEndLogonDelegate Is Nothing) Then
                Me.onEndLogonDelegate = AddressOf Me.OnEndLogon
            End If
            If (Me.onLogonCompletedDelegate Is Nothing) Then
                Me.onLogonCompletedDelegate = AddressOf Me.OnLogonCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginLogonDelegate, New Object() {poParameter}, Me.onEndLogonDelegate, Me.onLogonCompletedDelegate, userState)
        End Sub
        
        Public Function SetKey(ByVal pcKey As String) As String Implements LoginServiceRef.ILoginService.SetKey
            Return MyBase.Channel.SetKey(pcKey)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginSetKey(ByVal pcKey As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements LoginServiceRef.ILoginService.BeginSetKey
            Return MyBase.Channel.BeginSetKey(pcKey, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndSetKey(ByVal result As System.IAsyncResult) As String Implements LoginServiceRef.ILoginService.EndSetKey
            Return MyBase.Channel.EndSetKey(result)
        End Function
        
        Private Function OnBeginSetKey(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pcKey As String = CType(inValues(0),String)
            Return Me.BeginSetKey(pcKey, callback, asyncState)
        End Function
        
        Private Function OnEndSetKey(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As String = Me.EndSetKey(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnSetKeyCompleted(ByVal state As Object)
            If (Not (Me.SetKeyCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent SetKeyCompleted(Me, New SetKeyCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub SetKeyAsync(ByVal pcKey As String)
            Me.SetKeyAsync(pcKey, Nothing)
        End Sub
        
        Public Overloads Sub SetKeyAsync(ByVal pcKey As String, ByVal userState As Object)
            If (Me.onBeginSetKeyDelegate Is Nothing) Then
                Me.onBeginSetKeyDelegate = AddressOf Me.OnBeginSetKey
            End If
            If (Me.onEndSetKeyDelegate Is Nothing) Then
                Me.onEndSetKeyDelegate = AddressOf Me.OnEndSetKey
            End If
            If (Me.onSetKeyCompletedDelegate Is Nothing) Then
                Me.onSetKeyCompletedDelegate = AddressOf Me.OnSetKeyCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSetKeyDelegate, New Object() {pcKey}, Me.onEndSetKeyDelegate, Me.onSetKeyCompletedDelegate, userState)
        End Sub
        
        Public Function svc_getUserCompanyBroadcast(ByVal poParameter As LoginServiceRef.SAM_USER_COMPANYDTO) As LoginServiceRef.SAM_USER_COMPANYDTO Implements LoginServiceRef.ILoginService.svc_getUserCompanyBroadcast
            Return MyBase.Channel.svc_getUserCompanyBroadcast(poParameter)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function Beginsvc_getUserCompanyBroadcast(ByVal poParameter As LoginServiceRef.SAM_USER_COMPANYDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements LoginServiceRef.ILoginService.Beginsvc_getUserCompanyBroadcast
            Return MyBase.Channel.Beginsvc_getUserCompanyBroadcast(poParameter, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function Endsvc_getUserCompanyBroadcast(ByVal result As System.IAsyncResult) As LoginServiceRef.SAM_USER_COMPANYDTO Implements LoginServiceRef.ILoginService.Endsvc_getUserCompanyBroadcast
            Return MyBase.Channel.Endsvc_getUserCompanyBroadcast(result)
        End Function
        
        Private Function OnBeginsvc_getUserCompanyBroadcast(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poParameter As LoginServiceRef.SAM_USER_COMPANYDTO = CType(inValues(0),LoginServiceRef.SAM_USER_COMPANYDTO)
            Return Me.Beginsvc_getUserCompanyBroadcast(poParameter, callback, asyncState)
        End Function
        
        Private Function OnEndsvc_getUserCompanyBroadcast(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As LoginServiceRef.SAM_USER_COMPANYDTO = Me.Endsvc_getUserCompanyBroadcast(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub Onsvc_getUserCompanyBroadcastCompleted(ByVal state As Object)
            If (Not (Me.svc_getUserCompanyBroadcastCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent svc_getUserCompanyBroadcastCompleted(Me, New svc_getUserCompanyBroadcastCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub svc_getUserCompanyBroadcastAsync(ByVal poParameter As LoginServiceRef.SAM_USER_COMPANYDTO)
            Me.svc_getUserCompanyBroadcastAsync(poParameter, Nothing)
        End Sub
        
        Public Overloads Sub svc_getUserCompanyBroadcastAsync(ByVal poParameter As LoginServiceRef.SAM_USER_COMPANYDTO, ByVal userState As Object)
            If (Me.onBeginsvc_getUserCompanyBroadcastDelegate Is Nothing) Then
                Me.onBeginsvc_getUserCompanyBroadcastDelegate = AddressOf Me.OnBeginsvc_getUserCompanyBroadcast
            End If
            If (Me.onEndsvc_getUserCompanyBroadcastDelegate Is Nothing) Then
                Me.onEndsvc_getUserCompanyBroadcastDelegate = AddressOf Me.OnEndsvc_getUserCompanyBroadcast
            End If
            If (Me.onsvc_getUserCompanyBroadcastCompletedDelegate Is Nothing) Then
                Me.onsvc_getUserCompanyBroadcastCompletedDelegate = AddressOf Me.Onsvc_getUserCompanyBroadcastCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginsvc_getUserCompanyBroadcastDelegate, New Object() {poParameter}, Me.onEndsvc_getUserCompanyBroadcastDelegate, Me.onsvc_getUserCompanyBroadcastCompletedDelegate, userState)
        End Sub
        
        Public Function svc_getCompanyAndUserName(ByVal poParameter As LoginServiceRef.LoginDTO) As LoginServiceRef.LoginDTO Implements LoginServiceRef.ILoginService.svc_getCompanyAndUserName
            Return MyBase.Channel.svc_getCompanyAndUserName(poParameter)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function Beginsvc_getCompanyAndUserName(ByVal poParameter As LoginServiceRef.LoginDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements LoginServiceRef.ILoginService.Beginsvc_getCompanyAndUserName
            Return MyBase.Channel.Beginsvc_getCompanyAndUserName(poParameter, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function Endsvc_getCompanyAndUserName(ByVal result As System.IAsyncResult) As LoginServiceRef.LoginDTO Implements LoginServiceRef.ILoginService.Endsvc_getCompanyAndUserName
            Return MyBase.Channel.Endsvc_getCompanyAndUserName(result)
        End Function
        
        Private Function OnBeginsvc_getCompanyAndUserName(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poParameter As LoginServiceRef.LoginDTO = CType(inValues(0),LoginServiceRef.LoginDTO)
            Return Me.Beginsvc_getCompanyAndUserName(poParameter, callback, asyncState)
        End Function
        
        Private Function OnEndsvc_getCompanyAndUserName(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As LoginServiceRef.LoginDTO = Me.Endsvc_getCompanyAndUserName(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub Onsvc_getCompanyAndUserNameCompleted(ByVal state As Object)
            If (Not (Me.svc_getCompanyAndUserNameCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent svc_getCompanyAndUserNameCompleted(Me, New svc_getCompanyAndUserNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub svc_getCompanyAndUserNameAsync(ByVal poParameter As LoginServiceRef.LoginDTO)
            Me.svc_getCompanyAndUserNameAsync(poParameter, Nothing)
        End Sub
        
        Public Overloads Sub svc_getCompanyAndUserNameAsync(ByVal poParameter As LoginServiceRef.LoginDTO, ByVal userState As Object)
            If (Me.onBeginsvc_getCompanyAndUserNameDelegate Is Nothing) Then
                Me.onBeginsvc_getCompanyAndUserNameDelegate = AddressOf Me.OnBeginsvc_getCompanyAndUserName
            End If
            If (Me.onEndsvc_getCompanyAndUserNameDelegate Is Nothing) Then
                Me.onEndsvc_getCompanyAndUserNameDelegate = AddressOf Me.OnEndsvc_getCompanyAndUserName
            End If
            If (Me.onsvc_getCompanyAndUserNameCompletedDelegate Is Nothing) Then
                Me.onsvc_getCompanyAndUserNameCompletedDelegate = AddressOf Me.Onsvc_getCompanyAndUserNameCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginsvc_getCompanyAndUserNameDelegate, New Object() {poParameter}, Me.onEndsvc_getCompanyAndUserNameDelegate, Me.onsvc_getCompanyAndUserNameCompletedDelegate, userState)
        End Sub
        
        Public Function getLastUpdate(ByVal poParameter As LoginServiceRef.LoginDTO) As System.Nullable(Of Date) Implements LoginServiceRef.ILoginService.getLastUpdate
            Return MyBase.Channel.getLastUpdate(poParameter)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegingetLastUpdate(ByVal poParameter As LoginServiceRef.LoginDTO, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements LoginServiceRef.ILoginService.BegingetLastUpdate
            Return MyBase.Channel.BegingetLastUpdate(poParameter, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndgetLastUpdate(ByVal result As System.IAsyncResult) As System.Nullable(Of Date) Implements LoginServiceRef.ILoginService.EndgetLastUpdate
            Return MyBase.Channel.EndgetLastUpdate(result)
        End Function
        
        Private Function OnBegingetLastUpdate(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim poParameter As LoginServiceRef.LoginDTO = CType(inValues(0),LoginServiceRef.LoginDTO)
            Return Me.BegingetLastUpdate(poParameter, callback, asyncState)
        End Function
        
        Private Function OnEndgetLastUpdate(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As System.Nullable(Of Date) = Me.EndgetLastUpdate(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OngetLastUpdateCompleted(ByVal state As Object)
            If (Not (Me.getLastUpdateCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent getLastUpdateCompleted(Me, New getLastUpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub getLastUpdateAsync(ByVal poParameter As LoginServiceRef.LoginDTO)
            Me.getLastUpdateAsync(poParameter, Nothing)
        End Sub
        
        Public Overloads Sub getLastUpdateAsync(ByVal poParameter As LoginServiceRef.LoginDTO, ByVal userState As Object)
            If (Me.onBegingetLastUpdateDelegate Is Nothing) Then
                Me.onBegingetLastUpdateDelegate = AddressOf Me.OnBegingetLastUpdate
            End If
            If (Me.onEndgetLastUpdateDelegate Is Nothing) Then
                Me.onEndgetLastUpdateDelegate = AddressOf Me.OnEndgetLastUpdate
            End If
            If (Me.ongetLastUpdateCompletedDelegate Is Nothing) Then
                Me.ongetLastUpdateCompletedDelegate = AddressOf Me.OngetLastUpdateCompleted
            End If
            MyBase.InvokeAsync(Me.onBegingetLastUpdateDelegate, New Object() {poParameter}, Me.onEndgetLastUpdateDelegate, Me.ongetLastUpdateCompletedDelegate, userState)
        End Sub
        
        Public Sub doFlushData(ByVal pcUserId As String, ByVal pcCompanyId As String) Implements LoginServiceRef.ILoginService.doFlushData
            MyBase.Channel.doFlushData(pcUserId, pcCompanyId)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BegindoFlushData(ByVal pcUserId As String, ByVal pcCompanyId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements LoginServiceRef.ILoginService.BegindoFlushData
            Return MyBase.Channel.BegindoFlushData(pcUserId, pcCompanyId, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Sub EnddoFlushData(ByVal result As System.IAsyncResult) Implements LoginServiceRef.ILoginService.EnddoFlushData
            MyBase.Channel.EnddoFlushData(result)
        End Sub
        
        Private Function OnBegindoFlushData(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim pcUserId As String = CType(inValues(0),String)
            Dim pcCompanyId As String = CType(inValues(1),String)
            Return Me.BegindoFlushData(pcUserId, pcCompanyId, callback, asyncState)
        End Function
        
        Private Function OnEnddoFlushData(ByVal result As System.IAsyncResult) As Object()
            Me.EnddoFlushData(result)
            Return Nothing
        End Function
        
        Private Sub OndoFlushDataCompleted(ByVal state As Object)
            If (Not (Me.doFlushDataCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent doFlushDataCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub doFlushDataAsync(ByVal pcUserId As String, ByVal pcCompanyId As String)
            Me.doFlushDataAsync(pcUserId, pcCompanyId, Nothing)
        End Sub
        
        Public Overloads Sub doFlushDataAsync(ByVal pcUserId As String, ByVal pcCompanyId As String, ByVal userState As Object)
            If (Me.onBegindoFlushDataDelegate Is Nothing) Then
                Me.onBegindoFlushDataDelegate = AddressOf Me.OnBegindoFlushData
            End If
            If (Me.onEnddoFlushDataDelegate Is Nothing) Then
                Me.onEnddoFlushDataDelegate = AddressOf Me.OnEnddoFlushData
            End If
            If (Me.ondoFlushDataCompletedDelegate Is Nothing) Then
                Me.ondoFlushDataCompletedDelegate = AddressOf Me.OndoFlushDataCompleted
            End If
            MyBase.InvokeAsync(Me.onBegindoFlushDataDelegate, New Object() {pcUserId, pcCompanyId}, Me.onEnddoFlushDataDelegate, Me.ondoFlushDataCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
